/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * cccs_ticket.java
 *
 * Created on Feb 15, 2010, 6:11:22 PM
 */

package cc_orangetv;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.JTextField;
import java.awt.*;
import java.awt.Event.*;
import java.sql.*;
import javax.sun.database.JavaConnector;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import java.io.*;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.Calendar;
import java.util.Iterator;
import java.util.List;
import java.util.ArrayList;
import java.net.*;
import java.text.SimpleDateFormat;

/**
 *
 * @author jsm
 */
public class cccs_ticket extends javax.swing.JFrame {

    public static int id, contid, coun, no1, ticno, submit;
    public static boolean newtic=true, caltic=false;
    public static int ass = -1;
    private static boolean raction=false,raction1=false;

    String s, opdt, optm, catid, scateg;
    public static String deptid, usrlvl;

    public static int sla, statuss;
    private static int GT, GS, STORING, OTHERS, gtyes, gsyes, storingyes, othersyes;
    private static String replacement, rnarasi="", rnarasi1="", note;
//    private String note;
    /** Creates new form cccs_ticket */
    public cccs_ticket() {
        initComponents();
        setSize(1022,600);
        endcondition="";
        showDept();showProduct();
        showcategory();showSource();
        showType();showBussL();
        optm();
        opdt();
        id=-1;
        catdetailupadate=false;
        catfinalupadate=false;
//        submit=0;
//        klik2();
    }


     private cccs_History Hic;
    public cccs_ticket(cccs_History hic){
        this();
        this.Hic=hic;
    }
    private cccs_info inf;
    public cccs_ticket(cccs_info ifo){
        this();
        this.inf=ifo;
    }
    private cccs_Search_customer Src;
    public cccs_ticket(cccs_Search_customer src){
        this();
        this.Src=src;
    }
    public static ContactCenterOrangeTv CCanj;
    public cccs_ticket(ContactCenterOrangeTv ccanj){
        this();
        this.CCanj=ccanj;
    }
    private cccs_login Log;
    public cccs_ticket(cccs_login log){
        this();
        this.Log=log;
    }
    public static cccs_InBoundCall Inc;
    public cccs_ticket(cccs_InBoundCall inc){
        this();
        this.Inc=inc;
    }
    public static cccs_OutBound Obc;
    public cccs_ticket(cccs_OutBound obc){
        this();
        this.Obc=obc;
    }
    private cccs_Media Med;
    public cccs_ticket(cccs_Media med){
        this();
        this.Med=med;
    }
    private cccs_SMS Sms;
    public cccs_ticket(cccs_SMS sms){
        this();
        this.Sms=sms;
    }
    private cccs_EMail Mail;
    public cccs_ticket(cccs_EMail mail){
        this();
        this.Mail=mail;
    }
    private cccs_FAX1 Fax;
    public cccs_ticket(cccs_FAX1 fax){
        this();
        this.Fax=fax;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane5 = new javax.swing.JScrollPane();
        jPanel7 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtnotic = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbcategory = new javax.swing.JComboBox();
        cbprior = new javax.swing.JComboBox();
        cbdept = new javax.swing.JComboBox();
        btnreset = new javax.swing.JButton();
        tabdet = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        txtGuarantyNo = new javax.swing.JTextField();
        txtCusNam = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtcusfax = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtCusPho = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtcustadd = new javax.swing.JTextArea();
        jLabel24 = new javax.swing.JLabel();
        txtIdCust = new javax.swing.JTextField();
        btnSrchCus = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtPicHp = new javax.swing.JTextField();
        txtPicPho = new javax.swing.JTextField();
        txtPic = new javax.swing.JTextField();
        txtPicMail = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        txtPicAdd = new javax.swing.JTextArea();
        btncall = new javax.swing.JButton();
        btnfax = new javax.swing.JButton();
        btnmail = new javax.swing.JButton();
        btnsms = new javax.swing.JButton();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        cbTicketType = new javax.swing.JComboBox();
        jLabel56 = new javax.swing.JLabel();
        cbTicketSource = new javax.swing.JComboBox();
        jLabel59 = new javax.swing.JLabel();
        cbProduct = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        cbBussLine = new javax.swing.JComboBox();
        jPanel6 = new javax.swing.JPanel();
        btncreate = new javax.swing.JButton();
        btnhist = new javax.swing.JButton();
        cksubmit = new javax.swing.JCheckBox();
        btnhist1 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        btnclosed = new javax.swing.JButton();
        btncanc1 = new javax.swing.JButton();
        btncanc = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtlastnote = new javax.swing.JTextArea();
        jLabel51 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtdetails = new javax.swing.JTextArea();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        txtnote = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Ticket");
        setBackground(new java.awt.Color(204, 204, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "<<OPEN NEW TICKET>>", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 12))); // NOI18N
        jPanel1.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ticket No. :"); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(260, 20, 80, 20);

        txtnotic.setEditable(false);
        txtnotic.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtnotic.setEnabled(false);
        jPanel1.add(txtnotic);
        txtnotic.setBounds(340, 20, 140, 24);

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel2.setText("*Category :"); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 100, 100, 20);

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel6.setText("  Prority :"); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 20, 100, 20);

        cbcategory.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        cbcategory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbcategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbcategoryActionPerformed(evt);
            }
        });
        jPanel1.add(cbcategory);
        cbcategory.setBounds(120, 100, 300, 24);

        cbprior.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        cbprior.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NORMAL", "URGENT" }));
        jPanel1.add(cbprior);
        cbprior.setBounds(120, 20, 140, 24);

        cbdept.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        cbdept.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbdept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbdeptActionPerformed(evt);
            }
        });
        jPanel1.add(cbdept);
        cbdept.setBounds(120, 80, 360, 24);

        btnreset.setFont(new java.awt.Font("Calibri", 0, 10)); // NOI18N
        btnreset.setText("Reset");
        btnreset.setIconTextGap(0);
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });
        jPanel1.add(btnreset);
        btnreset.setBounds(420, 100, 60, 24);

        tabdet.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.setLayout(null);

        jLabel23.setBackground(new java.awt.Color(102, 102, 255));
        jLabel23.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel23.setText(" Id :"); // NOI18N
        jPanel4.add(jLabel23);
        jLabel23.setBounds(10, 10, 100, 20);

        txtGuarantyNo.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jPanel4.add(txtGuarantyNo);
        txtGuarantyNo.setBounds(110, 30, 360, 24);

        txtCusNam.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jPanel4.add(txtCusNam);
        txtCusNam.setBounds(110, 50, 360, 24);

        jLabel7.setBackground(new java.awt.Color(102, 102, 255));
        jLabel7.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel7.setText("*Cust. Name :"); // NOI18N
        jPanel4.add(jLabel7);
        jLabel7.setBounds(4, 50, 100, 20);

        jLabel8.setBackground(new java.awt.Color(102, 102, 255));
        jLabel8.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Cust.Fax :"); // NOI18N
        jPanel4.add(jLabel8);
        jLabel8.setBounds(240, 70, 100, 20);

        txtcusfax.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jPanel4.add(txtcusfax);
        txtcusfax.setBounds(340, 70, 130, 24);

        jLabel10.setBackground(new java.awt.Color(102, 102, 255));
        jLabel10.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel10.setText("Cust. Phone :"); // NOI18N
        jPanel4.add(jLabel10);
        jLabel10.setBounds(10, 70, 100, 20);

        txtCusPho.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jPanel4.add(txtCusPho);
        txtCusPho.setBounds(110, 70, 130, 24);

        jLabel21.setBackground(new java.awt.Color(102, 102, 255));
        jLabel21.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel21.setText("Cust address:"); // NOI18N
        jPanel4.add(jLabel21);
        jLabel21.setBounds(10, 90, 100, 20);

        txtcustadd.setColumns(20);
        txtcustadd.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtcustadd.setLineWrap(true);
        txtcustadd.setRows(5);
        jScrollPane6.setViewportView(txtcustadd);

        jPanel4.add(jScrollPane6);
        jScrollPane6.setBounds(110, 90, 360, 60);

        jLabel24.setBackground(new java.awt.Color(102, 102, 255));
        jLabel24.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel24.setText(" Bike Point Name :"); // NOI18N
        jPanel4.add(jLabel24);
        jLabel24.setBounds(10, 30, 100, 20);

        txtIdCust.setEditable(false);
        txtIdCust.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtIdCust.setEnabled(false);
        jPanel4.add(txtIdCust);
        txtIdCust.setBounds(110, 10, 140, 24);

        btnSrchCus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/1245117595_001_37.png"))); // NOI18N
        btnSrchCus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSrchCusActionPerformed(evt);
            }
        });
        jPanel4.add(btnSrchCus);
        btnSrchCus.setBounds(250, 10, 24, 24);

        tabdet.addTab("Customer", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel5.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel13.setText("Cordinator :"); // NOI18N
        jPanel5.add(jLabel13);
        jLabel13.setBounds(10, 10, 100, 20);

        jLabel14.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel14.setText("Phone :"); // NOI18N
        jPanel5.add(jLabel14);
        jLabel14.setBounds(10, 30, 100, 20);

        jLabel20.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel20.setText("Email :"); // NOI18N
        jPanel5.add(jLabel20);
        jLabel20.setBounds(10, 70, 100, 20);

        txtPicHp.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtPicHp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPicHpActionPerformed(evt);
            }
        });
        jPanel5.add(txtPicHp);
        txtPicHp.setBounds(110, 50, 360, 24);

        txtPicPho.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jPanel5.add(txtPicPho);
        txtPicPho.setBounds(110, 30, 360, 24);

        txtPic.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jPanel5.add(txtPic);
        txtPic.setBounds(110, 10, 360, 24);

        txtPicMail.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtPicMail.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtPicMailCaretUpdate(evt);
            }
        });
        txtPicMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPicMailActionPerformed(evt);
            }
        });
        jPanel5.add(txtPicMail);
        txtPicMail.setBounds(110, 70, 360, 24);

        jLabel57.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel57.setText("Address :"); // NOI18N
        jPanel5.add(jLabel57);
        jLabel57.setBounds(10, 90, 100, 20);

        jLabel58.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel58.setText("Handphone :"); // NOI18N
        jPanel5.add(jLabel58);
        jLabel58.setBounds(10, 50, 100, 20);

        txtPicAdd.setColumns(20);
        txtPicAdd.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtPicAdd.setLineWrap(true);
        txtPicAdd.setRows(5);
        jScrollPane12.setViewportView(txtPicAdd);

        jPanel5.add(jScrollPane12);
        jScrollPane12.setBounds(110, 90, 360, 60);

        tabdet.addTab("PIC", jPanel5);

        jPanel1.add(tabdet);
        tabdet.setBounds(10, 160, 492, 240);

        btncall.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        btncall.setForeground(new java.awt.Color(0, 153, 51));
        btncall.setText("Call");
        btncall.setEnabled(false);
        btncall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncallActionPerformed(evt);
            }
        });
        jPanel1.add(btncall);
        btncall.setBounds(240, 400, 60, 25);

        btnfax.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        btnfax.setForeground(new java.awt.Color(0, 153, 51));
        btnfax.setText("Fax");
        btnfax.setEnabled(false);
        btnfax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfaxActionPerformed(evt);
            }
        });
        jPanel1.add(btnfax);
        btnfax.setBounds(430, 400, 60, 0);

        btnmail.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        btnmail.setForeground(new java.awt.Color(0, 153, 51));
        btnmail.setText("Email");
        btnmail.setEnabled(false);
        btnmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmailActionPerformed(evt);
            }
        });
        jPanel1.add(btnmail);
        btnmail.setBounds(360, 400, 70, 25);

        btnsms.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        btnsms.setForeground(new java.awt.Color(0, 153, 51));
        btnsms.setText("Sms");
        btnsms.setEnabled(false);
        btnsms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsmsActionPerformed(evt);
            }
        });
        jPanel1.add(btnsms);
        btnsms.setBounds(300, 400, 60, 25);

        jLabel54.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel54.setText("*Department :"); // NOI18N
        jPanel1.add(jLabel54);
        jLabel54.setBounds(20, 80, 100, 20);

        jLabel55.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel55.setText("*Product :"); // NOI18N
        jPanel1.add(jLabel55);
        jLabel55.setBounds(20, 60, 100, 20);

        cbTicketType.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        cbTicketType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbTicketType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTicketTypeActionPerformed(evt);
            }
        });
        cbTicketType.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbTicketTypeFocusLost(evt);
            }
        });
        jPanel1.add(cbTicketType);
        cbTicketType.setBounds(340, 40, 140, 24);

        jLabel56.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel56.setText(" *Ticket type :"); // NOI18N
        jPanel1.add(jLabel56);
        jLabel56.setBounds(260, 40, 80, 20);

        cbTicketSource.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        cbTicketSource.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbTicketSource.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTicketSourceActionPerformed(evt);
            }
        });
        cbTicketSource.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbTicketSourceFocusLost(evt);
            }
        });
        jPanel1.add(cbTicketSource);
        cbTicketSource.setBounds(120, 40, 140, 24);

        jLabel59.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel59.setText("*Ticket Source :"); // NOI18N
        jPanel1.add(jLabel59);
        jLabel59.setBounds(20, 40, 100, 20);

        cbProduct.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        cbProduct.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbProductActionPerformed(evt);
            }
        });
        cbProduct.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbProductFocusLost(evt);
            }
        });
        jPanel1.add(cbProduct);
        cbProduct.setBounds(120, 60, 360, 24);

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel3.setText("  Bussiness Line :"); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 120, 100, 20);

        cbBussLine.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        cbBussLine.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbBussLine.setEnabled(false);
        cbBussLine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBussLineActionPerformed(evt);
            }
        });
        jPanel1.add(cbBussLine);
        cbBussLine.setBounds(120, 120, 360, 24);

        jPanel7.add(jPanel1);
        jPanel1.setBounds(10, 10, 510, 440);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Action", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 12))); // NOI18N
        jPanel6.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jPanel6.setLayout(null);

        btncreate.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btncreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/1.jpg"))); // NOI18N
        btncreate.setText("Submit"); // NOI18N
        btncreate.setToolTipText("Create Ticket"); // NOI18N
        btncreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btncreateMouseEntered(evt);
            }
        });
        btncreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncreateActionPerformed(evt);
            }
        });
        jPanel6.add(btncreate);
        btncreate.setBounds(10, 20, 130, 40);

        btnhist.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnhist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/hi.jpg"))); // NOI18N
        btnhist.setText("History"); // NOI18N
        btnhist.setToolTipText("History"); // NOI18N
        btnhist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnhistMouseClicked(evt);
            }
        });
        jPanel6.add(btnhist);
        btnhist.setBounds(230, 20, 120, 40);

        cksubmit.setBackground(new java.awt.Color(204, 204, 255));
        cksubmit.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        cksubmit.setSelected(true);
        cksubmit.setText("Submit");
        cksubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cksubmitMouseClicked(evt);
            }
        });
        jPanel6.add(cksubmit);
        cksubmit.setBounds(140, 20, 90, 20);

        btnhist1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnhist1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/z.jpg"))); // NOI18N
        btnhist1.setText("Media"); // NOI18N
        btnhist1.setToolTipText("History"); // NOI18N
        btnhist1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnhist1MouseClicked(evt);
            }
        });
        jPanel6.add(btnhist1);
        btnhist1.setBounds(355, 20, 110, 40);

        jPanel7.add(jPanel6);
        jPanel6.setBounds(530, 10, 480, 70);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Action", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 12))); // NOI18N
        jPanel9.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jPanel9.setLayout(null);

        btnclosed.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnclosed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/comp.jpg"))); // NOI18N
        btnclosed.setText("Closed"); // NOI18N
        btnclosed.setToolTipText("Closed Ticket"); // NOI18N
        btnclosed.setEnabled(false);
        btnclosed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclosedActionPerformed(evt);
            }
        });
        jPanel9.add(btnclosed);
        btnclosed.setBounds(10, 20, 110, 40);

        btncanc1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btncanc1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/cancel.jpg"))); // NOI18N
        btncanc1.setText("Cancel"); // NOI18N
        btncanc1.setToolTipText("Cancel"); // NOI18N
        btncanc1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncanc1MouseClicked(evt);
            }
        });
        btncanc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncanc1ActionPerformed(evt);
            }
        });
        jPanel9.add(btncanc1);
        btncanc1.setBounds(10, 20, 110, 0);

        btncanc.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btncanc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/exit.jpg"))); // NOI18N
        btncanc.setText("Exit"); // NOI18N
        btncanc.setToolTipText("EXIT"); // NOI18N
        btncanc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancActionPerformed(evt);
            }
        });
        jPanel9.add(btncanc);
        btncanc.setBounds(380, 20, 90, 40);

        jPanel7.add(jPanel9);
        jPanel9.setBounds(530, 480, 480, 70);

        txtlastnote.setColumns(20);
        txtlastnote.setEditable(false);
        txtlastnote.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtlastnote.setLineWrap(true);
        txtlastnote.setRows(5);
        jScrollPane4.setViewportView(txtlastnote);

        jPanel7.add(jScrollPane4);
        jScrollPane4.setBounds(540, 210, 460, 230);

        jLabel51.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(51, 51, 255));
        jLabel51.setText("Details :");
        jPanel7.add(jLabel51);
        jLabel51.setBounds(540, 80, 60, 10);

        txtdetails.setColumns(20);
        txtdetails.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtdetails.setLineWrap(true);
        txtdetails.setRows(5);
        jScrollPane1.setViewportView(txtdetails);

        jPanel7.add(jScrollPane1);
        jScrollPane1.setBounds(540, 90, 460, 90);

        jLabel52.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(51, 51, 255));
        jLabel52.setText("Last Note :");
        jPanel7.add(jLabel52);
        jLabel52.setBounds(540, 200, 100, 10);

        jLabel53.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(51, 51, 255));
        jLabel53.setText("Note :");
        jPanel7.add(jLabel53);
        jLabel53.setBounds(20, 450, 60, 10);

        txtnote.setColumns(20);
        txtnote.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtnote.setLineWrap(true);
        txtnote.setRows(5);
        jScrollPane11.setViewportView(txtnote);

        jPanel7.add(jScrollPane11);
        jScrollPane11.setBounds(20, 460, 490, 90);

        jScrollPane5.setViewportView(jPanel7);

        getContentPane().add(jScrollPane5);
        jScrollPane5.setBounds(0, 0, 1020, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btnhistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhistMouseClicked
        // TODO add your handling code here:
        cccs_History hic = new cccs_History();
        hic.setVisible(true);

        Hic.no=id;
        Hic.ticid=Integer.valueOf((String)txtnotic.getText());
        Hic.klik2();
    }//GEN-LAST:event_btnhistMouseClicked

    private void btncancActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancActionPerformed
        // TODO add your handling code here:
        dispose();
        CCanj.ticshow=false;
    }//GEN-LAST:event_btncancActionPerformed

    private void txtPicHpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPicHpActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtPicHpActionPerformed

    private void btncreateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncreateMouseEntered
        // TODO add your handling code here:
//        if (txtPicHp.getText().equals("")){
//            JOptionPane.showMessageDialog(null, "Cso Mail cannot be empty !!", "MAILING",JOptionPane.WARNING_MESSAGE);
//        }
    }//GEN-LAST:event_btncreateMouseEntered

    private void cksubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cksubmitMouseClicked
        // TODO add your handling code here:
        if(cksubmit.isSelected()==true){
            btnclosed.setEnabled(false);
            submit=1;
            btncreate.setText("Submit");
            
        }else{
            btnclosed.setEnabled(true);
            submit=0;
            if(newtic==true){
                btncreate.setText("Created");
            }else{
                btncreate.setText("Save");
            }
        }
    }//GEN-LAST:event_cksubmitMouseClicked

    private void btncanc1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncanc1MouseClicked
        // TODO add your handling code here:
        opdt();
        optm();
        int i=JOptionPane.showConfirmDialog(null, "Data will be changes","SAVE",JOptionPane.YES_NO_OPTION);
        if (i==JOptionPane.YES_OPTION){
            sql="update tickets set _status=-1, cancel_date='"+opdt+"', cancel_time='"+optm+"', cancel_username='"+CCanj.lbluser.getText()+"' where ticket_id='"+id+"'";
            CCanj.jconn.SQLExecute(sql,CCanj.conn);
            sql2="insert into log_tickets (log_date,log_time,username,user_level,ticket_id,_status,info) values ('"+opdt+"','"+optm+"','"+CCanj.lbluser.getText()+"','"+usrlvl+"','"+id+"',-1,'ticket canceled by : "+CCanj.lbluser.getText()+"\n"+opdt+"\n"+optm+"\n\n"+txtdetails.getText()+" \n\n "+txtlastnote.getText()+"')";
            CCanj.jconn.SQLExecute(sql2,CCanj.conn);
        }
    }//GEN-LAST:event_btncanc1MouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        btncall.setEnabled(false);
        btnfax.setEnabled(false);
        btnmail.setEnabled(false);
        btnsms.setEnabled(false);
        CCanj.ticshow=false;
//        try {
//            conn.close();
//        } catch (SQLException ex) {
//            System.err.println(ex.getMessage());
//        }
    }//GEN-LAST:event_formWindowClosed

    private void btnhist1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhist1MouseClicked
        // TODO add your handling code here:
        cccs_Media med = new cccs_Media();
        med.setVisible(true);

        Med.no=id;
        Med.tno=txtnotic.getText();
        Med.tabelmedia();
    }//GEN-LAST:event_btnhist1MouseClicked

    private void txtPicMailCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtPicMailCaretUpdate
        // TODO add your handling code here:
}//GEN-LAST:event_txtPicMailCaretUpdate

    private void txtPicMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPicMailActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtPicMailActionPerformed

    private void btnfaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfaxActionPerformed
        // TODO add your handling code here:
        cccs_FAX1 fax = new cccs_FAX1();
        fax.setVisible(true);

        if(tabdet.getSelectedIndex()==0 && !txtcusfax.getText().equals("")){
            Fax.txtcto.setText(txtcusfax.getText());
        }
        if(tabdet.getSelectedIndex()==1 && !txtPicPho.getText().equals("")){
            Fax.txtcto.setText(txtPicPho.getText());
        }

        Fax.txtnotic.setText(txtnotic.getText());
        Fax.id=id;
        Fax.faxtic=true;
}//GEN-LAST:event_btnfaxActionPerformed

    private void btncallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncallActionPerformed
        // TODO add your handling code here:
        cccs_OutBound out = new cccs_OutBound();
        out.setVisible(true);

        if(tabdet.getSelectedIndex()==0){
            Obc.txtdial.setText(txtCusPho.getText());
        }
        if(tabdet.getSelectedIndex()==1){
            Obc.txtdial.setText(txtPicPho.getText());
        }
        Obc.txtnotic1.setText(String.valueOf(id));
        Obc.txtnotic.setText(txtnotic.getText());
        Obc.obtic=true;

        Obc.klik2();
}//GEN-LAST:event_btncallActionPerformed

    private void btnmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmailActionPerformed
        // TODO add your handling code here:
        cccs_EMail mail = new cccs_EMail();
        mail.setVisible(true);

        if(tabdet.getSelectedIndex()==0){
            Mail.txtcto.setText(txtCusNam.getText());
        }
        if(tabdet.getSelectedIndex()==1){
            Mail.txtcto.setText(txtPicMail.getText());
        }
        Mail.txtnotic.setText(txtnotic.getText());
        Mail.txtIdCust.setText(txtIdCust.getText());
        Mail.id=id;
        Mail.mailtic=true;
    }//GEN-LAST:event_btnmailActionPerformed

    private void btncreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncreateActionPerformed
        // TODO add your handling code here:
        opdt();
        optm();
        if (txtPicHp.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Pic phone cannot be empty !! Ticket Cannot be Created", "Ticketing",JOptionPane.WARNING_MESSAGE);
        }else{
            if(cksubmit.isSelected()==true){
                submit=1;
            }else{
                submit=0;
            }      
            if (newtic==true){
                System.out.print("\nnewtic=true "+newtic);
                if (inputValid()==true || txtPicHp.getText().equals("")){
                    getdept();
                    getcateg();
                    usrlvl();
                    try{
                        sql="insert into tickets set _status=0, dept_id='"+deptid+"', category_id='"+catid+"', category='"+cbcategory.getSelectedItem()+"'"
                                + ", source_id='"+cbTicketSource.getSelectedIndex()+"', bussiness_line_id='"+cbBussLine.getSelectedIndex()+"'"
                                + ", product_id='"+cbProduct.getSelectedIndex()+"', product='"+cbProduct.getSelectedItem()+"'"
                                + ", _type='"+cbTicketType.getSelectedItem()+"', assign_dept='"+deptid+"', _priority='"+cbprior.getSelectedIndex()+"', sla='"+sla+"'"
                                + ", bikepoint_id='"+txtIdCust.getText()+"', bikepoint_name='"+txtGuarantyNo.getText()+"'"
                                + ", cust_name='"+txtCusNam.getText()+"', cust_address='"+txtcustadd.getText()+"'"
                                + ", cust_phone='"+txtCusPho.getText()+"', cust_fax='"+txtcusfax.getText()+"'"
                                + ", pic_name='"+txtPic.getText()+"', pic_phone='"+txtPicPho.getText()+"', pic_mobile='"+txtPicHp.getText()+"'"
                                + ", pic_email='"+txtPicMail.getText()+"', pic_address='"+txtPicAdd.getText()+"'"
                                + ", details='"+txtdetails.getText()+"'"
                                + ", note='"+CCanj.lbluser.getText()+"@"+opdt.substring(8,10)+"/"+opdt.substring(5,7)+"/"+opdt.substring(0,4)+" "+optm.replace(':','.')+" : "
                                    + "\nCategory : "+cbcategory.getSelectedItem()+""
                                    + "\n"+txtnote.getText()+"==='"
                                + ", open_date='"+opdt+"', open_time='"+optm+"', open_username='"+CCanj.lbluser.getText()+"', open_dept='"+Log.deptid+"'"
                                + ", _submitted='"+submit+"'";
                        CCanj.jconn.SQLExecute(sql,CCanj.conn);
                        sqlid="select distinct last_insert_id() from tickets";
                        rs=CCanj.jconn.SQLExecuteRS(sqlid, CCanj.conn);
                          while (rs.next()) {
                            id =Integer.parseInt(rs.getString(1));
                          }
                        sqlco="select count(*) from tickets where year(open_date)=year(CURRENT_DATE) and month(open_date)=month(CURRENT_DATE) and ticket_id < '"+id+"'";
                        rs1=CCanj.jconn.SQLExecuteRS(sqlco,CCanj.conn);
                        while (rs1.next()) {
                            coun =Integer.parseInt(rs1.getString(1));
                        }
                        coun=coun+1;
                        System.out.print("\nisi no coun = "+coun+"\n");
                        sqlno="update tickets set ticket_no=concat(right(YEAR(CURRENT_DATE),2),lpad(Month(Current_date),2,'0'),lpad('"+coun+"',4,'0')) where ticket_id='"+id+"'";
                        CCanj.jconn.SQLExecute(sqlno, CCanj.conn);
                        sqlno1="select ticket_no from tickets where ticket_id = '"+id+"'";
                        rs0=CCanj.jconn.SQLExecuteRS(sqlno1,CCanj.conn);
                        while (rs0.next()) {
                            no1 =Integer.parseInt(rs0.getString(1));
                        }
                        sql2="insert into log_tickets"
                                + " (log_date,log_time,username,user_level,ticket_id,_status"
                                + " ,info,ticket_no)"
                                + " values"
                                + " ('"+opdt+"','"+optm+"','"+CCanj.lbluser.getText()+"','"+usrlvl+"','"+id+"',0"
                                + ", 'TICKET OPENED "
                                + "\n\n Category : "+cbcategory.getSelectedItem()+""
                                + "\n\n"+txtdetails.getText()+" \n\n "+txtnote.getText()+","
                                + "\n"+rnarasi+"','"+no1+"')";
                        CCanj.jconn.SQLExecute(sql2,CCanj.conn);
                        if(submit==0){
                            JOptionPane.showMessageDialog(null, "TICKET "+no1+" CREATED", "TICKETING",JOptionPane.WARNING_MESSAGE);
                        }else{
                            JOptionPane.showMessageDialog(null, "TICKET "+no1+" SUBMITED", "TICKETING",JOptionPane.WARNING_MESSAGE);
                            CCanj.s = "TICKET|ASSIGN|"+deptid+"|"+no1+"\r\n";
                            CCanj.kirimBroad();
                            sql1="insert into log_mail (mail_date,mail_time"
                                    + ",mail_from,mail_to"
//                                    + ",mail_cc,mail_bcc"
                                    + ",mail_subject,mail_text"
                                    + ",ticket_id,ticket_no,direction,username) values "
                                    + "(CURRENT_DATE,CURRENT_TIME"
                                    + ",'castrolcare@jsm.co.id','"+txtPicMail.getText()+"'"
//                                    + ",'idabagus@polytron.co.id','rusli@jsm.co.id'"
                                    + ",'<Ticket>#"+txtCusNam.getText()+"#"+cbcategory.getSelectedItem()+"#"+no1+"','Details :\n"+txtdetails.getText()+"\n\nSoluiton :\n"+txtlastnote.getText()+" \n\n Action Status : "+rnarasi+"\n\n SUBMITED'"
                                    + ",'"+id+"','"+no1+"',1,'"+CCanj.lbluser.getText()+"')";
                            CCanj.jconn.SQLExecute(sql1,CCanj.conn);

//                            sql2="insert into log_sms (sms_date,sms_time,username,sms_to,ticket_id,ticket_no"
//                                    + ",sms_text,_direction,_status)"
//                                    + " values"
//                                    + " ('"+opdt+"','"+optm+"','"+CCanj.lbluser.getText()+"','"+txtPicHp.getText()+"','"+id+"','"+no1+"'"
//                                    + ",'Anda mendapat 1 ticket permintaan baru No. Ticket "+no1+"',1,0)";
//                            CCanj.jconn.SQLExecute(sql2,CCanj.conn);
//                            CCanj.s = "SMS|OUTBOUND\r\n";
//                            CCanj.kirimBroad();
                            JOptionPane.showMessageDialog(null, "EMAIL SENT", "MAILING",JOptionPane.WARNING_MESSAGE);
                        }                        
                    }catch(Exception e){
                        System.out.println(e);
                    }
                    CCanj.s = "MAIL|OUTBOUND\r\n";CCanj.kirimBroad();
                    newtic=false;
                }else{
                    JOptionPane.showMessageDialog(null,"Data Incomplete, Please fill it first , You cannot created ticket");
                }
            }else{
                System.out.print("\nnewtic = false = "+newtic);
                System.out.print("\nsubmit = 0 = "+ submit);
                    getdept();
                    getcateg();
                    usrlvl();
                    if(ass==-1){
                        ass=Integer.parseInt(deptid);
                    }
                    sql="update tickets set dept_id='"+deptid+"' ,category_id='"+catid+"' "
                            + ", category='"+cbcategory.getSelectedItem()+"', _type='"+cbTicketType.getSelectedItem()+"' "
                            + ", source_id='"+cbTicketSource.getSelectedIndex()+"', bussiness_line_id='"+cbBussLine.getSelectedIndex()+"'"
                            + ", product_id='"+cbProduct.getSelectedIndex()+"', product='"+cbProduct.getSelectedItem()+"'"
                            + ", assign_dept='"+ass+"' ,_priority='"+cbprior.getSelectedIndex()+"' ,sla='"+sla+"' "
                            + ", bikepoint_id='"+txtIdCust.getText()+"', bikepoint_name='"+txtGuarantyNo.getText()+"'"
                            + ", cust_name='"+txtCusNam.getText()+"', cust_address='"+txtcustadd.getText()+"'"
                            + ", cust_phone='"+txtCusPho.getText()+"', cust_fax='"+txtcusfax.getText()+"'"
                            + ", pic_name='"+txtPic.getText()+"', pic_phone='"+txtPicPho.getText()+"', pic_mobile='"+txtPicHp.getText()+"'"
                            + ", pic_email='"+txtPicMail.getText()+"', pic_address='"+txtPicAdd.getText()+"'"
                            + ",details='"+txtdetails.getText()+"' "
                            + ",note='"+CCanj.lbluser.getText()+"@"+opdt.substring(8,10)+"/"+opdt.substring(5,7)+"/"+opdt.substring(0,4)+" "+optm.replace(':','.')+" : "
                                + "\n"+txtnote.getText()+"==="
                                + "\n"+txtlastnote.getText()+"' "
                            + ", _submitted='"+submit+"' where ticket_id='"+id+"'";
                    CCanj.jconn.SQLExecute(sql,CCanj.conn);
                    if (statuss==0 && ass==0){
                        sql3="update tickets set _status=1, process_date='"+opdt+"', process_time='"+optm+"', process_username='"+CCanj.lbluser.getText()+"' where ticket_id='"+id+"' and ticket_no='"+txtnotic.getText()+"'";
                        CCanj.jconn.SQLExecute(sql3,CCanj.conn);
                        statuss=1;
                    }
                    sql2="insert into log_tickets (log_date,log_time,username,user_level,ticket_id,info,ticket_no,_status) values ('"+opdt+"','"+optm+"','"+CCanj.lbluser.getText()+"','"+usrlvl+"','"+id+"','"+txtnote.getText()+"','"+txtnotic.getText()+"','"+statuss+"')";
                    CCanj.jconn.SQLExecute(sql2,CCanj.conn);
                    if(submit==1){
                        JOptionPane.showMessageDialog(null, "TICKET "+txtnotic.getText()+" SUBMITED", "TICKETING",JOptionPane.WARNING_MESSAGE);
                        sql1="insert into log_mail (mail_date,mail_time"
                                + ",mail_from,mail_to"
//                                + ",mail_cc,mail_bcc"
                                + ",mail_subject,mail_text"
                                + ",ticket_id,ticket_no,direction,username)"
                                + " values"
                                + " (CURRENT_DATE,CURRENT_TIME"
                                + ",'castrolcare@jsm.co.id','"+txtPicMail.getText()+"'"
//                                + ",'idabagus@polytron.co.id','rusli@jsm.co.id'"
                                + ",'<Ticket>#"+txtCusNam.getText()+"#"+cbcategory.getSelectedItem()+"#"+txtnotic.getText()+"','Submitted by : "+CCanj.lbluser.getText()+"\n"+opdt+"\n"+optm+"\n\n"+txtdetails.getText()+"\n\n"+txtlastnote.getText()+"\n\n Action Status : "+rnarasi+"'"
                                + ",'"+id+"','"+txtnotic.getText()+"',1,'"+CCanj.lbluser.getText()+"')";
                        CCanj.jconn.SQLExecute(sql1,CCanj.conn);
                        CCanj.s = "TICKET|ASSIGN|"+deptid+"|"+txtnotic.getText()+"\r\n";
                        CCanj.kirimBroad();
                        sql2="insert into log_tickets"
                                + " (log_date,log_time,username,user_level,ticket_id,_status"
                                + " ,info,ticket_no)"
                                + " values"
                                + " ('"+opdt+"','"+optm+"','"+CCanj.lbluser.getText()+"','"+usrlvl+"','"+id+"',0"
                                + ", 'TICKET Submited "
                                + "\n\n Submit to : "+cbdept.getSelectedItem()+""
                                + "\n Submit by : "+CCanj.lbluser.getText()+"@"+opdt.substring(8,10)+"/"+opdt.substring(5,7)+"/"+opdt.substring(0,4)+" "+optm.replace(':','.')+" : "
                                + "\n\n"+txtdetails.getText()+" \n\n "+txtnote.getText()+","
                                + "\n"+rnarasi+"','"+no1+"')";
                        CCanj.jconn.SQLExecute(sql2,CCanj.conn);
//                        sql2="insert into log_sms (sms_date,sms_time,username,sms_to,ticket_id,ticket_no"
//                                + ",sms_text,_direction,_status)"
//                                + " values"
//                                + " ('"+opdt+"','"+optm+"','"+CCanj.lbluser.getText()+"','"+txtPicHp.getText()+"','"+id+"','"+txtnotic.getText()+"'"
//                                + ",'Anda mendapat 1 ticket permintaan baru No. Ticket "+txtnotic.getText()+"',1,0)";
//                        CCanj.jconn.SQLExecute(sql2,CCanj.conn);
//                        CCanj.s = "SMS|OUTBOUND\r\n";
//                        CCanj.kirimBroad();
                        JOptionPane.showMessageDialog(null, "EMAIL SENT", "MAILING",JOptionPane.WARNING_MESSAGE);
                    }else{
                        JOptionPane.showMessageDialog(null, "TICKET UPDATED", "TICKETING",JOptionPane.WARNING_MESSAGE);                 
                        CCanj.s = "TICKET|UPDATE|"+deptid+"|"+txtnotic.getText()+"\r\n";
                        CCanj.kirimBroad();
//                        JOptionPane.showMessageDialog(null, "EMAIL SENT", "MAILING",JOptionPane.WARNING_MESSAGE);
                    }
                System.out.print("\nsubmit = 1 = "+ submit);

            }//end of validasi newticket
        }//end of validasi txtcso
        if(result==true){bersih();dispose();}
        CCanj.tabeltic();
        if(caltic==true){
            Obc.txtnotic1.setText(Integer.toString(no1));
        }
    }//GEN-LAST:event_btncreateActionPerformed

    private void btnclosedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclosedActionPerformed
        // TODO add your handling code here:
        cccs_Closed_tic clo= new cccs_Closed_tic();
        clo.setVisible(true);
    }//GEN-LAST:event_btnclosedActionPerformed

    private void btncanc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncanc1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncanc1ActionPerformed

    private void btnsmsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsmsActionPerformed
        // TODO add your handling code here:
        cccs_SMS sms = new cccs_SMS();
        sms.setVisible(true);

        if(tabdet.getSelectedIndex()==0){
            Sms.txtto.setText(txtCusPho.getText());
        }
        if(tabdet.getSelectedIndex()==1){
            Sms.txtto.setText(txtPicPho.getText());
        }
        Sms.txtnotic.setText(txtnotic.getText());
        Sms.txtIdCust.setText(txtIdCust.getText());
        Sms.id=id;
        Sms.smstic=true;
}//GEN-LAST:event_btnsmsActionPerformed

    public boolean catdetailupadate=false;
    public boolean catfinalupadate=false;
    private void cbTicketTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTicketTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTicketTypeActionPerformed

    private void cbTicketTypeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbTicketTypeFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTicketTypeFocusLost

    private void cbdeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbdeptActionPerformed
        // TODO add your handling code here:
        if(raction==true){
            if(cbdept.getSelectedIndex()==-1){
                showcategory();
                cbBussLine.setSelectedIndex(-1);
            }else{
                endcondition=" and dept_id='"+cbdept.getSelectedIndex()+"'";
                showcategory();
                cbcategory.setSelectedItem(scateg);
            }
        }
    }//GEN-LAST:event_cbdeptActionPerformed

    private void cbTicketSourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTicketSourceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTicketSourceActionPerformed

    private void cbTicketSourceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbTicketSourceFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTicketSourceFocusLost

    private void cbProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbProductActionPerformed

    private void cbProductFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbProductFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_cbProductFocusLost

    private void cbcategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbcategoryActionPerformed
        // TODO add your handling code here:
        if(raction1==true){
            if(cbcategory.getSelectedIndex()==-1){
                txtPic.setText("");
                txtPicPho.setText("");
                txtPicHp.setText("");
                txtPicMail.setText("");
                txtPicAdd.setText("");
                cbBussLine.setSelectedIndex(-1);
                scateg=null;
            }else{
                scateg=String.valueOf(cbcategory.getSelectedItem());
                try {
                    sql1 = "select * from _ticketcategory"
                            + " left join _pic on _ticketcategory.pic_id=_pic.pic_id"
                            + " where category_name='"+cbcategory.getSelectedItem()+"' and _ticketcategory._deleted=0 ";
                    rs1 = CCanj.jconn.SQLExecuteRS(sql1, CCanj.conn);
                    while (rs1.next()) {
                        if(cbdept.getSelectedIndex()==-1){
                            cbdept.setSelectedIndex(Integer.parseInt(rs1.getString("dept_id")));
                        }
                        cbBussLine.setSelectedIndex(Integer.parseInt(rs1.getString("bussiness_line_id")));
                        sla=Integer.parseInt(rs1.getString("sla"));
                        txtPic.setText(rs1.getString("pic_name"));
                        txtPicHp.setText(rs1.getString("pic_phone"));
                        txtPicMail.setText(rs1.getString("pic_email"));
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(cccs_ticket.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_cbcategoryActionPerformed

    private void cbBussLineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBussLineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbBussLineActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        // TODO add your handling code here:
        endcondition="";
        showcategory();
        showDept();
        cbBussLine.setSelectedIndex(-1);
    }//GEN-LAST:event_btnresetActionPerformed

    private void btnSrchCusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSrchCusActionPerformed
        // TODO add your handling code here:
        cccs_Search_customer srcus= new cccs_Search_customer();
        srcus.setVisible(true);
        
        srcus.Form=1;
    }//GEN-LAST:event_btnSrchCusActionPerformed

boolean result;
private boolean inputValid(){        
//        if((cbcategory.getSelectedItem().equals("NON CUSTOMER"))){
//            result=true;
//        }else{
            if((cbcategory.getSelectedIndex()==-1)||(cbdept.getSelectedIndex()==-1)||(txtCusNam.getText().equals(""))||
                (cbTicketSource.getSelectedIndex()==-1)||(cbTicketType.getSelectedIndex()==-1)||(cbProduct.getSelectedIndex()==-1)){
                JOptionPane.showMessageDialog(null,"Fill All mandatory field first \nwhich has stars mark(*)");
                result=false;
            }else
                result=true;
//            }   
        return result;
    }
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cccs_ticket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSrchCus;
    public static javax.swing.JButton btncall;
    private javax.swing.JButton btncanc;
    private javax.swing.JButton btncanc1;
    public static javax.swing.JButton btnclosed;
    public static javax.swing.JButton btncreate;
    public static javax.swing.JButton btnfax;
    private javax.swing.JButton btnhist;
    private javax.swing.JButton btnhist1;
    public static javax.swing.JButton btnmail;
    private javax.swing.JButton btnreset;
    public static javax.swing.JButton btnsms;
    public static javax.swing.JComboBox cbBussLine;
    public static javax.swing.JComboBox cbProduct;
    public static javax.swing.JComboBox cbTicketSource;
    public static javax.swing.JComboBox cbTicketType;
    public static javax.swing.JComboBox cbcategory;
    public static javax.swing.JComboBox cbdept;
    public static javax.swing.JComboBox cbprior;
    public static javax.swing.JCheckBox cksubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    public static javax.swing.JTabbedPane tabdet;
    public static javax.swing.JTextField txtCusNam;
    public static javax.swing.JTextField txtCusPho;
    public static javax.swing.JTextField txtGuarantyNo;
    public static javax.swing.JTextField txtIdCust;
    public static javax.swing.JTextField txtPic;
    public static javax.swing.JTextArea txtPicAdd;
    public static javax.swing.JTextField txtPicHp;
    public static javax.swing.JTextField txtPicMail;
    public static javax.swing.JTextField txtPicPho;
    public static javax.swing.JTextField txtcusfax;
    public static javax.swing.JTextArea txtcustadd;
    public static javax.swing.JTextArea txtdetails;
    public static javax.swing.JTextArea txtlastnote;
    public static javax.swing.JTextArea txtnote;
    public static javax.swing.JTextField txtnotic;
    // End of variables declaration//GEN-END:variables

    public static String sql, sql1,sql2,sql3,sqlid;
    public static String sqlco, sqlno,sqlno1;
    public static ResultSet rs0,rs,rs1;
    public static String ticid,endcondition;

    public static void klik(){
        raction=false;raction1=false;
        if ((id==0)){
            System.out.println("ififififif");
            System.out.println(id);
        }else{
            try{
                sql="select tickets.*, _department.dept_name from tickets"
                        + " join _department on tickets.dept_id=_department.dept_id"
                        + " where ticket_id='"+id+"' ";
//                System.out.println("Sql klik : "+sql);
                rs0=CCanj.jconn.SQLExecuteRS(sql,CCanj.conn);
                while(rs0.next()){
    //                txtnotic.setText(rs.getString(1));
                    statuss=Integer.parseInt(rs0.getString("_status"));
                    cbcategory.setSelectedItem(rs0.getString("category"));
                    cbTicketType.setSelectedItem(rs0.getString("_type"));
                    cbprior.setSelectedIndex(Integer.parseInt(rs0.getString("_priority")));
                    cbdept.setSelectedItem(rs0.getString("dept_name"));
                    ass=Integer.parseInt(rs0.getString("assign_dept"));
                    cbProduct.setSelectedItem(rs0.getString("product"));
                    cbTicketSource.setSelectedIndex(Integer.parseInt(rs0.getString("source_id")));
                    cbBussLine.setSelectedIndex(Integer.parseInt(rs0.getString("bussiness_line_id")));
                    txtIdCust.setText(rs0.getString("bikepoint_id"));
                    txtGuarantyNo.setText(rs0.getString("bikepoint_name"));
                    txtCusNam.setText(rs0.getString("cust_name"));
                    txtCusPho.setText(rs0.getString("cust_phone"));
                    txtcusfax.setText(rs0.getString("cust_fax"));
                    txtcustadd.setText(rs0.getString("cust_address"));
                    txtPic.setText(rs0.getString("pic_name"));
                    txtPicPho.setText(rs0.getString("pic_phone"));
                    txtPicHp.setText(rs0.getString("pic_mobile"));
                    txtPicMail.setText(rs0.getString("pic_email"));
                    txtPicAdd.setText(rs0.getString("pic_address"));
                    txtdetails.setText(rs0.getString("details"));
                    submit=Integer.parseInt(rs0.getString("_submitted"));
                    txtlastnote.setText(rs0.getString("note"));
                    note=(String)rs0.getString("note");
                }
            }catch(Exception e){
                System.out.println(e);
            }
        }
        if(submit==1){
            cksubmit.setSelected(true);
            cksubmit.setEnabled(false);
            if(cbprior.getSelectedIndex()==0){
                btncreate.setEnabled(true);
                btncreate.setText("Update");
            }else{
                btncreate.setEnabled(false);
                btncreate.setText("Submitted");
            }
            if(ass==0){
                btncreate.setEnabled(true);
                btncreate.setText("Save");
            }
        }else{
            cksubmit.setSelected(false);
            btncreate.setText("Save");
            btnclosed.setEnabled(true);
        }
        if(newtic==false && CCanj.cbdirection.getSelectedItem().equals("OUTBOUND") && CCanj.btnready.getText().equals("Unregis")){
            btncall.setEnabled(true);            btnfax.setEnabled(true);
            btnmail.setEnabled(true);            btnsms.setEnabled(true);
        }
        if(statuss==2){
            btnclosed.setEnabled(true);
        }
        raction=true;raction1=true;
    }

     private void showcategory()    {
         raction1=false;
         try{
             cbcategory.removeAllItems();             
             sql="select category_name, sla from _ticketcategory where _deleted=0 ";
             sql=sql+endcondition;
             rs=CCanj.jconn.SQLExecuteRS(sql,CCanj.conn);
             while(rs.next()){
                 cbcategory.addItem(rs.getString(1));
                 sla=Integer.parseInt(rs.getString("sla"));
             }
             endcondition="";
             cbcategory.setSelectedIndex(-1);
         }catch(Exception e){
             System.out.println(e);
         }
         raction1=true;
     }
     
     private void showDept(){
         raction=false;
         try{
             cbdept.removeAllItems();             
             sql="select dept_name from _department where _deleted=0 ";
             sql=sql+endcondition;
             rs=CCanj.jconn.SQLExecuteRS(sql,CCanj.conn);
             while(rs.next()){
                 cbdept.addItem(rs.getString(1));
             }
             endcondition="";
             cbdept.setSelectedIndex(-1);
         }catch(Exception e){
             System.out.println(e);
         }
         raction=true;
     }
     
     public static void showProduct(){
          cbProduct.removeAllItems();
          try{
              sql="select data from _product";
              rs=CCanj.jconn.SQLExecuteRS(sql,CCanj.conn);
              while(rs.next()){
                  cbProduct.addItem(rs.getString(1));
              }
              cbProduct.setSelectedIndex(-1);
          }catch(Exception e){
              System.out.println(e);
          }
      }

      private void showType(){
          cbTicketType.removeAllItems();
          try{
              sql="select data from _tickettype order by code";
              rs=CCanj.jconn.SQLExecuteRS(sql,CCanj.conn);
              while(rs.next()){
                  cbTicketType.addItem(rs.getString(1));
              }
              cbTicketType.setSelectedIndex(-1);
          }catch(Exception e){
              System.out.println(e);
          }
      }
      private void showSource(){
          cbTicketSource.removeAllItems();
          try{
              sql="select data from _callertype order by code";
              rs=CCanj.jconn.SQLExecuteRS(sql,CCanj.conn);
              while(rs.next()){
                  cbTicketSource.addItem(rs.getString(1));
              }
              cbTicketSource.setSelectedIndex(-1);
          }catch(Exception e){
              System.out.println(e);
          }
      }
      private void showBussL(){
          cbBussLine.removeAllItems();
          try{
              sql="select data from _bussinesline order by code";
              rs=CCanj.jconn.SQLExecuteRS(sql,CCanj.conn);
              while(rs.next()){
                  cbBussLine.addItem(rs.getString(1));
              }
              cbBussLine.setSelectedIndex(-1);
          }catch(Exception e){
              System.out.println(e);
          }
      }

      private void getdept(){
          try{
              sql="select dept_id from _department where dept_name='"+cbdept.getSelectedItem()+"'";
              rs=CCanj.jconn.SQLExecuteRS(sql,CCanj.conn);
              while(rs.next()){
                  deptid=rs.getString(1);
              }
          }catch(Exception e){
              System.out.print(e);
          }
      }

      private void getcateg(){
           try{
               sql="select category_id from _ticketcategory where category_name='"+cbcategory.getSelectedItem()+"' and dept_id='"+deptid+"' and _deleted=0";
               rs=CCanj.jconn.SQLExecuteRS(sql,CCanj.conn);
               while(rs.next()){
                   catid=rs.getString(1);
               }
           }catch(Exception e){
               System.out.print(e);
           }
      }
      public static void usrlvl(){
          try{
             sql="select _level from user_account where username='"+CCanj.lbluser.getText()+"'";
             rs=CCanj.jconn.SQLExecuteRS(sql, CCanj.conn);
             while(rs.next()){
                 usrlvl=rs.getString(1);
             }
         }catch(Exception e){
             System.out.print(e);
         }
     }

         

    void bersih(){
        txtnotic.setText("");       cbprior.setSelectedItem("NORMAL");
        cbcategory.setSelectedIndex(-1);        cbdept.setSelectedIndex(-1);
        cbProduct.setSelectedIndex(-1);        cbBussLine.setSelectedIndex(-1);
        cbTicketSource.setSelectedIndex(-1);        cbTicketType.setSelectedIndex(-1);

        txtCusNam.setText("");        txtcusfax.setText("");
        txtCusPho.setText("");        txtcustadd.setText("");
        
        txtGuarantyNo.setText("");
        txtPic.setText("");        txtPicPho.setText("");
        txtPicHp.setText("");        txtPicMail.setText("");
        txtPicAdd.setText("");
        txtdetails.setText("");
    }


    private void opdt(){
          try{
              sql="select CURRENT_DATE";
              rs = CCanj.jconn.SQLExecuteRS(sql, CCanj.conn);
              while(rs.next()){
                  opdt=rs.getString(1);
              }
          }catch(Exception exc){
              System.err.println(exc.getMessage());
          }
    }

        private void optm(){
            try{
              sql="select CURRENT_TIME";
              rs = CCanj.jconn.SQLExecuteRS(sql, CCanj.conn);
              while(rs.next()){
                  optm=rs.getString(1);
              }
          }catch(Exception exc){
              System.err.println(exc.getMessage());
          }
        }

}