/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * cccs_SMS.java
 *
 * Created on Feb 15, 2010, 4:45:48 PM
 */

package cc_orangetv;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import java.awt.*;
import java.awt.Event.*;
import java.sql.*;
import javax.sun.database.JavaConnector;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import java.io.*;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.Calendar;
import java.util.Iterator;
import java.util.List;
import java.util.ArrayList;
import java.net.*;

/**
 *
 * @author jsm
 */
public class cccs_SMS extends javax.swing.JFrame {

        String in[]=new String[12];
    String ou[]=new String[8];
    String s;
    String optm;
    String opdt;
    int l=160;
    int p=0;
    String limit;
    public static boolean smstic = false;
    public static int id, status, asdep;

    private String usrlvl, solution;
    public static String IdCust=null;
    /** Creates new form cccs_SMS */
    public cccs_SMS() {
        initComponents();
        setSize(524,269);
        usrlvl();
//        smstic=false;
        limit = txtmsg.getText();
        showCaltype();
//        p=limit.length();
    }

     private ContactCenterOrangeTv CCanj;
    public cccs_SMS(ContactCenterOrangeTv ccanj){
        this();
        this.CCanj=ccanj;
    }
    private cccs_ticket Tic;
    public cccs_SMS(cccs_ticket tic){
        this();
        this.Tic=tic;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtmsg = new javax.swing.JTextArea();
        lbllimit = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnsend = new javax.swing.JButton();
        btncancel = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtnotic = new javax.swing.JTextField();
        btnsrchcus = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cbdraft = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        cbcaltype = new javax.swing.JComboBox();
        jLabel23 = new javax.swing.JLabel();
        txtIdCust = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SMS");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane1.setBackground(new java.awt.Color(74, 99, 148));
        jTabbedPane1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel1.setText("draft :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 70, 100, 20);

        txtto.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jPanel1.add(txtto);
        txtto.setBounds(110, 10, 200, 24);

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel2.setText("messages :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 50, 100, 20);

        txtmsg.setColumns(20);
        txtmsg.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtmsg.setLineWrap(true);
        txtmsg.setRows(5);
        txtmsg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtmsgMouseExited(evt);
            }
        });
        txtmsg.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtmsgCaretUpdate(evt);
            }
        });
        txtmsg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtmsgKeyTyped(evt);
            }
        });
        jScrollPane3.setViewportView(txtmsg);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(110, 50, 370, 86);

        lbllimit.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lbllimit.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbllimit.setText("160");
        jPanel1.add(lbllimit);
        lbllimit.setBounds(110, 140, 18, 20);

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel4.setText("Characters Left");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(130, 140, 100, 20);

        btnsend.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        btnsend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/sms sent.jpg"))); // NOI18N
        btnsend.setEnabled(false);
        btnsend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsendActionPerformed(evt);
            }
        });
        jPanel1.add(btnsend);
        btnsend.setBounds(330, 140, 70, 40);

        btncancel.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        btncancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/sms canc.jpg"))); // NOI18N
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });
        jPanel1.add(btncancel);
        btncancel.setBounds(410, 140, 70, 40);

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Ticket No.");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(310, 10, 70, 0);

        txtnotic.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jPanel1.add(txtnotic);
        txtnotic.setBounds(380, 10, 100, 0);

        btnsrchcus.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        btnsrchcus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/1245117595_001_37.png"))); // NOI18N
        btnsrchcus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsrchcusMouseClicked(evt);
            }
        });
        btnsrchcus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsrchcusActionPerformed(evt);
            }
        });
        jPanel1.add(btnsrchcus);
        btnsrchcus.setBounds(460, 10, 20, 0);

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel3.setText("to :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 10, 100, 20);

        cbdraft.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        cbdraft.setMaximumRowCount(12);
        cbdraft.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pengiriman storing", "Pengiriman derek", "Keluhan kendaraan (Data tidak lengkap)", "Keluhan kendaraan (Data lengkap)", "Keluhan driver       (Data tidak lengkap)", "Keluhan driver       (Data lengkap)", "Keluhan marketing (Data tidak lengkap)", "Keluhan marketing (Data lengkap)", "Permintaan Data", "Ucapan terima kasih", "Customer minta dihubungi", "Umum" }));
        cbdraft.setSelectedIndex(11);
        cbdraft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbdraftActionPerformed(evt);
            }
        });
        jPanel1.add(cbdraft);
        cbdraft.setBounds(10, 90, 100, 24);

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel6.setText("Direction Type");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 30, 100, 20);

        cbcaltype.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        cbcaltype.setMaximumRowCount(9);
        cbcaltype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Non-customer", "Customer-Driver", "Customer-User", "Customer-PIC", "Customer-Other", "Internal-ANJ", "Internal-CC", "Internal-CSO", "Internal-Driver", "Internal-Other" }));
        cbcaltype.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbcaltypeMouseClicked(evt);
            }
        });
        jPanel1.add(cbcaltype);
        cbcaltype.setBounds(110, 30, 200, 24);

        jLabel23.setBackground(new java.awt.Color(102, 102, 255));
        jLabel23.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText(" Id :"); // NOI18N
        jPanel1.add(jLabel23);
        jLabel23.setBounds(310, 30, 70, 0);

        txtIdCust.setEditable(false);
        txtIdCust.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtIdCust.setEnabled(false);
        jPanel1.add(txtIdCust);
        txtIdCust.setBounds(380, 30, 100, 0);

        jTabbedPane1.addTab("Compose", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 530, 250);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btncancelActionPerformed

    private void btnsrchcusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsrchcusMouseClicked
        // TODO add your handling code here:
        cccs_Search_ticket st = new cccs_Search_ticket();
        st.setVisible(true);
}//GEN-LAST:event_btnsrchcusMouseClicked

    private void txtmsgKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmsgKeyTyped
        // TODO add your handling code here:
        if(evt.getKeyChar()==8){
            if(p<=0){
            }else{
                txtmsg.setEditable(true);
                l+=1;
                p-=1;
                lbllimit.setText(String.valueOf(l));
            }
        }else if (p<=159){
            l--;
            p++;
            lbllimit.setText(String.valueOf(l));
        }else{
            txtmsg.setEditable(false);
        }
    }//GEN-LAST:event_txtmsgKeyTyped

    private void txtmsgCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtmsgCaretUpdate
        // TODO add your handling code here:
        int panjang,t;
        String sms,isi;
        if(txtmsg.getText().length()>=160){
            sms=txtmsg.getText();
            isi=sms.substring(0,159);
            txtmsg.setText((String)isi);
            p=txtmsg.getText().length();
            l=160-p;
            lbllimit.setText(String.valueOf(l));
        }else{
            p=txtmsg.getText().length();
            l=160-p;
            lbllimit.setText(String.valueOf(l));
        }
    }//GEN-LAST:event_txtmsgCaretUpdate

    private void txtmsgMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtmsgMouseExited
        // TODO add your handling code here:
        int panjang,t;
        String sms,isi;
        if(txtmsg.getText().length()>=160){
            sms=txtmsg.getText();
            isi=sms.substring(0,159);
            txtmsg.setText((String)isi);
            p=txtmsg.getText().length();
            l=160-p;
            lbllimit.setText(String.valueOf(l));
        }else{
            p=txtmsg.getText().length();
            l=160-p;
            lbllimit.setText(String.valueOf(l));
        }
    }//GEN-LAST:event_txtmsgMouseExited

    private void cbdraftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbdraftActionPerformed
        // TODO add your handling code here:
        if(cbdraft.getSelectedIndex()==0){
            txtmsg.setText("Pelanggan Yth. Kami akan segera mengirimkan mobil service ke lokasi Anda. Mohon kesediaannya untuk menunggu. Tks");
        }
        if(cbdraft.getSelectedIndex()==1){
            txtmsg.setText("Pelanggan Yth. kami akan segera mengirimkan bantuan derek ke lokasi Anda. Mohon kesediaannya untuk menunggu. Tks");
        }
        if(cbdraft.getSelectedIndex()==2){
            txtmsg.setText("Pelanggan Yth. kami akan segera menindaklanjuti keluhan kendaraan Anda. Mohon mencantumkan no plat, nama, company, telp, dan, lokasi Anda saat ini. Tks");
        }
        if(cbdraft.getSelectedIndex()==3){
            txtmsg.setText("Pelanggan Yth. kami akan segera menindaklanjuti keluhan kendaraan Anda. Mohon kesediaannya untuk menunggu. Tks");
        }
        if(cbdraft.getSelectedIndex()==4){
            txtmsg.setText("Pelanggan Yth. kami akan segera menindaklanjuti keluhan tentang driver Anda. Mohon menginformasikan nama driver Anda. Tks");
        }
        if(cbdraft.getSelectedIndex()==5){
            txtmsg.setText("Pelanggan Yth. kami akan segera menindaklanjuti keluhan tentang driver Anda. Mohon informasikan kapan kami dapat memanggil driver untuk klarifikasi. Tks");
        }
        if(cbdraft.getSelectedIndex()==6){
            txtmsg.setText("Pelanggan Yth. kami akan segera menindaklanjuti keluhan/permintaan Anda. Mohon menginformasikan no plat, nama, company dan, telp Anda. Tks");
        }
        if(cbdraft.getSelectedIndex()==7){
            txtmsg.setText("Pelanggan Yth. kami akan segera menindaklanjuti keluhan/permintaan Anda. Tks");
        }
        if(cbdraft.getSelectedIndex()==8){
            txtmsg.setText("Pelanggan Yth. mengenai keluhan/permintaan Anda tentang xxxx, kami mohon informasi berupa xxxx. Tks");
        }
        if(cbdraft.getSelectedIndex()==9){
            txtmsg.setText("Terima kasih atas informasi Anda.");
        }
        if(cbdraft.getSelectedIndex()==10){
            txtmsg.setText("Pelanggan Yth. petugas kami akan segera menghubungi Anda. Tks");
        }
        if(cbdraft.getSelectedIndex()==11){
            txtmsg.setText("");
        }
}//GEN-LAST:event_cbdraftActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void cbcaltypeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbcaltypeMouseClicked
        // TODO add your handling code here:
        btnsend.setEnabled(true);
    }//GEN-LAST:event_cbcaltypeMouseClicked

    private void btnsendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsendActionPerformed
        // TODO add your handling code here:
        opdt();
        optm();
        stt();
        if (valid()==true){
            sql="insert into log_sms (sms_date,sms_time,username,sms_to,ticket_id,sms_text,_direction,direction_type,_status"
                    + ",ticket_no,bikepoint_id)"
                    + " values"
                    + " ('"+opdt+"','"+optm+"','"+CCanj.lbluser.getText()+"','"+txtto.getText()+"','"+id+"','"+txtmsg.getText()+"',1,'"+cbcaltype.getSelectedItem()+"',0"
                    + ",'"+txtnotic.getText()+"','"+txtIdCust.getText()+"')";
            CCanj.jconn.SQLExecute(sql,CCanj.conn);
            CCanj.s = "SMS|OUTBOUND\r\n";
            CCanj.kirimBroad();
            JOptionPane.showMessageDialog(null, "SMS SENT", "MESSAGING",JOptionPane.WARNING_MESSAGE);
        }
        if(smstic==true){
            if (status==0 && asdep==0){
                sql="update tickets set _status=1, process_date='"+opdt+"', process_time='"+optm+"', process_username='"+CCanj.lbluser.getText()+"' where ticket_id='"+Tic.id+"' and ticket_no='"+txtnotic.getText()+"'";
                CCanj.jconn.SQLExecute(sql,CCanj.conn);
                status=1;
            }
            sql1="insert into log_tickets (log_date,log_time,username,user_level,ticket_id,_status,info,ticket_no) values ('"+opdt+"','"+optm+"','"+CCanj.lbluser.getText()+"','"+usrlvl+"','"+Tic.id+"','"+status+"','Outgoing sms \nTo : "+txtto.getText()+" \n\n "+txtmsg.getText()+"','"+txtnotic.getText()+"')";
            CCanj.jconn.SQLExecute(sql1, CCanj.conn);
            try{
                sql2="select note from tickets where ticket_id='"+Tic.id+"'";
                rs = CCanj.jconn.SQLExecuteRS(sql2, CCanj.conn);
                while(rs.next()){
                    solution=rs.getString(1);
                }
            }catch(Exception exc){
                System.err.println(exc.getMessage());
            }
            sql3="update tickets set note='"+solution+"\n"+CCanj.lbluser.getText()+"@"+opdt.substring(8, 10) + "/" + opdt.substring(5, 7) + "/" + opdt.substring(0, 4)+"\n"+optm.replaceAll(":",".")+"\nOutgoing sms \nTo : "+txtto.getText()+" \n\n "+txtmsg.getText()+"\n===' where ticket_id='"+Tic.id+"'";
            CCanj.jconn.SQLExecute(sql3,CCanj.conn);
        }
        smstic=false;
    }//GEN-LAST:event_btnsendActionPerformed

    private void btnsrchcusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsrchcusActionPerformed
        // TODO add your handling code here:
        cccs_Search_customer srcus= new cccs_Search_customer();
        srcus.setVisible(true);
        
        srcus.Form=31;
        srcus.txtPhoneNo.setText(txtto.getText());   
        srcus.tabelcus();
        srcus.tabeltic();
    }//GEN-LAST:event_btnsrchcusActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cccs_SMS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btnsend;
    private javax.swing.JButton btnsrchcus;
    public static javax.swing.JComboBox cbcaltype;
    private javax.swing.JComboBox cbdraft;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbllimit;
    public static javax.swing.JTextField txtIdCust;
    private javax.swing.JTextArea txtmsg;
    public static javax.swing.JTextField txtnotic;
    public static javax.swing.JTextField txtto;
    // End of variables declaration//GEN-END:variables


    private String sql;
    private String sql1;
    private String sql2;
    private String sql3;
    private ResultSet rs;
//    private JavaConnector jconn=new JavaConnector();
//    private Connection conn;

    private boolean valid(){
        boolean result;
        if(txtto.getText().equals("")||txtmsg.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Data must be complete","MESSAGING",JOptionPane.WARNING_MESSAGE);
            result=false;
        }else{
            result=true;
        }
        return result;
    }
    
    private void bersih(){
        txtto.setText("");
        txtmsg.setText("");
            //txtNim.requestFocus();
    }
            
                 private void opdt(){
          try{
              sql="select CURRENT_DATE";
              rs = CCanj.jconn.SQLExecuteRS(sql, CCanj.conn);
              while(rs.next()){
                  opdt=rs.getString(1);
              }
          }catch(Exception exc){
              System.err.println(exc.getMessage());
          }
    }

        private void optm(){
            try{
              sql="select CURRENT_TIME";
              rs = CCanj.jconn.SQLExecuteRS(sql, CCanj.conn);
              while(rs.next()){
                  optm=rs.getString(1);
              }
          }catch(Exception exc){
              System.err.println(exc.getMessage());
          }
        }
        private void usrlvl(){
                try{
                    sql="select _level from user_account where username='"+CCanj.lbluser.getText()+"'";
                    rs=CCanj.jconn.SQLExecuteRS(sql, CCanj.conn);
                    while(rs.next()){
                        usrlvl=rs.getString(1);
                    }
                }catch(Exception e){
                    System.out.print(e);
                }
            }
        private void stt(){
                try{
                    sql="select _status, assign_dept from tickets where ticket_id='"+Tic.id+"' and ticket_no='"+txtnotic.getText()+"'";
                    rs=CCanj.jconn.SQLExecuteRS(sql, CCanj.conn);
                    while(rs.next()){
                        status=Integer.parseInt(rs.getString(1));
                        asdep=Integer.parseInt(rs.getString(2));
                    }
                }catch(Exception e){
                    System.out.print(e);
                }
            }
        private void showCaltype(){
        try{
            cbcaltype.removeAllItems();

            sql="select data from _callertype";
            rs=CCanj.jconn.SQLExecuteRS(sql,CCanj.conn);
            while(rs.next()){
                cbcaltype.addItem(rs.getString(1));
            }
        }catch(Exception e){
            System.out.println(e);

        }
    }
}
