/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * cccs_InBoundCall.java
 *
 * Created on Feb 15, 2010, 10:52:51 AM
 */

package cc_orangetv;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.Timer;
import java.awt.*;
import java.awt.Event.*;
import java.awt.event.ActionEvent;
import java.sql.*;
import javax.sun.database.JavaConnector;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import java.io.*;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.PrintWriter;
import java.util.Date;
import java.util.Calendar;
import java.util.Iterator;
import java.util.List;
import java.util.ArrayList;
import java.net.*;
import java.text.SimpleDateFormat;
import java.util.GregorianCalendar;

/**
 *
 * @author jsm
 */
public class cccs_InBoundCall extends javax.swing.JFrame {
    public static int sco=0,x=0;
    String s;
    public static String tic[]=new String[20];
    public static String cus[]=new String[20];

    private String condition;
    public static String clbk=null, IdCust=null, cldt=null;
    public static long elapsed;
    public static long busy;

    String pabx;
    String in_ext;
    String out_ext;
//    String loid=null;
    public static Timer ti;
    public static Timer ab;
    public static int blankcall, wrongnum, inquiry, complaint, suggest, inqtrans;
    public static int ticid, xxx=0, xx=0;
    public static String loid;
   public static boolean hangup = false;


    /** Creates new form cccs_InBoundCall */
    public cccs_InBoundCall() {
        initComponents();
        loid=CCanj.loid;
        txtcalnum.setText("");
        txtcalnum.setText(CCanj.callid);
        txtcalnm.getText().toUpperCase();
        lbldurasi.setText("");
        suggest=0;blankcall=0;inquiry=0;complaint=0;wrongnum=0;inqtrans=0;
        this.setSize(1025,530);
        tblcall.setModel(tabcall);
        tbltic.setModel(tabticconf);
        tbcus(tblcall,new int []{100,120,100,100,150    ,100,150,150,500,80     ,-1});
        tbcus(tbltic,new int []{100,100,100,100,120      ,150,300,200,200,150
                ,250,200,150,250,120        ,250,500,500,-1});
        showCaltype();showCat1();showCat2();showCat3();showCat4();
//        showCust();
            ab= new Timer(1000, acw);
        tabelcall();
    }

    public static cccs_login Log;
    public cccs_InBoundCall(cccs_login log){
        this();
        this.Log=log;
    }

    public static ContactCenterOrangeTv CCanj;
    public cccs_InBoundCall(ContactCenterOrangeTv ccanj){
        this();
        this.CCanj=ccanj;
    }
    public cccs_ticket Tic;
    public cccs_InBoundCall(cccs_ticket tic){
        this();
        this.Tic=tic;
    }
    private cccs_History Hic;
    public cccs_InBoundCall(cccs_History hic){
        this();
        this.Hic=hic;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtcalnum = new javax.swing.JTextField();
        txtcalnm = new javax.swing.JTextField();
        ckblank = new javax.swing.JCheckBox();
        ckwrongno = new javax.swing.JCheckBox();
        ckinqui = new javax.swing.JCheckBox();
        ckcompl = new javax.swing.JCheckBox();
        btnHangUp = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtareacom = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtnotic = new javax.swing.JTextField();
        btnexpand = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();
        btnopentic = new javax.swing.JButton();
        btnsave = new javax.swing.JButton();
        lbldurasi = new javax.swing.JLabel();
        cbcaltype = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        cbcust = new javax.swing.JComboBox();
        btnmute = new javax.swing.JButton();
        ckHold = new javax.swing.JCheckBox();
        cksugges = new javax.swing.JCheckBox();
        ckinqui1 = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();
        cbsendertype = new javax.swing.JComboBox();
        cbInq = new javax.swing.JComboBox();
        cbInqTr = new javax.swing.JComboBox();
        cbComp = new javax.swing.JComboBox();
        cbSugges = new javax.swing.JComboBox();
        txtnotic1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtnotic2 = new javax.swing.JTextField();
        txtlogid = new javax.swing.JTextField();
        txtlogid1 = new javax.swing.JTextField();
        txtlogid2 = new javax.swing.JTextField();
        txtlogid3 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbltic = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnsrch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblcall = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        txtIdCust = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("INBOUND CALL");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 204));
        jLabel1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel1.setText("Caller Number");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(20, 40, 90, 20);

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel2.setText("*Name");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(20, 60, 90, 20);

        txtcalnum.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jPanel2.add(txtcalnum);
        txtcalnum.setBounds(110, 40, 200, 24);

        txtcalnm.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jPanel2.add(txtcalnm);
        txtcalnm.setBounds(110, 60, 200, 24);
        txtcalnm.getText().toUpperCase();

        ckblank.setBackground(new java.awt.Color(255, 255, 255));
        ckblank.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        ckblank.setText("BLANK CALL");
        ckblank.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ckblankMouseClicked(evt);
            }
        });
        ckblank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckblankActionPerformed(evt);
            }
        });
        jPanel2.add(ckblank);
        ckblank.setBounds(10, 10, 90, 20);

        ckwrongno.setBackground(new java.awt.Color(255, 255, 255));
        ckwrongno.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        ckwrongno.setText("WRONG NUMBER");
        ckwrongno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckwrongnoActionPerformed(evt);
            }
        });
        jPanel2.add(ckwrongno);
        ckwrongno.setBounds(190, 10, 120, 20);

        ckinqui.setBackground(new java.awt.Color(255, 255, 255));
        ckinqui.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        ckinqui.setText("*INQUIRY");
        ckinqui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckinquiActionPerformed(evt);
            }
        });
        jPanel2.add(ckinqui);
        ckinqui.setBounds(10, 110, 100, 20);

        ckcompl.setBackground(new java.awt.Color(255, 255, 255));
        ckcompl.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        ckcompl.setText("*COMPLAINT");
        ckcompl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckcomplActionPerformed(evt);
            }
        });
        jPanel2.add(ckcompl);
        ckcompl.setBounds(10, 150, 100, 20);

        btnHangUp.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnHangUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/4.jpg"))); // NOI18N
        btnHangUp.setText("Hang UP");
        btnHangUp.setEnabled(false);
        btnHangUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHangUpMouseEntered(evt);
            }
        });
        btnHangUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHangUpActionPerformed(evt);
            }
        });
        jPanel2.add(btnHangUp);
        btnHangUp.setBounds(170, 450, 140, 20);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "*Comment", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 11))); // NOI18N

        txtareacom.setColumns(20);
        txtareacom.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtareacom.setLineWrap(true);
        txtareacom.setRows(5);
        jScrollPane2.setViewportView(txtareacom);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3);
        jPanel3.setBounds(10, 270, 300, 180);

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel3.setText("Caller Type");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 90, 100, 0);

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel4.setText("Kode Distributor");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 200, 90, 20);

        txtnotic.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jPanel2.add(txtnotic);
        txtnotic.setBounds(110, 200, 200, 24);

        btnexpand.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnexpand.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/1245117595_001_37.png"))); // NOI18N
        btnexpand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexpandActionPerformed(evt);
            }
        });
        jPanel2.add(btnexpand);
        btnexpand.setBounds(210, 100, 20, 0);

        btnreset.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnreset.setText("Reset");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });
        jPanel2.add(btnreset);
        btnreset.setBounds(240, 100, 70, 0);

        btnopentic.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnopentic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/tic.jpg"))); // NOI18N
        btnopentic.setText("Open Ticket");
        btnopentic.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnopentic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnopenticActionPerformed(evt);
            }
        });
        jPanel2.add(btnopentic);
        btnopentic.setBounds(170, 220, 140, 0);

        btnsave.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnsave.setText("Save");
        btnsave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsaveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnsaveMouseEntered(evt);
            }
        });
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        jPanel2.add(btnsave);
        btnsave.setBounds(10, 450, 70, 24);

        lbldurasi.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbldurasi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbldurasi.setToolTipText("");
        jPanel2.add(lbldurasi);
        lbldurasi.setBounds(80, 450, 90, 20);

        cbcaltype.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        cbcaltype.setMaximumRowCount(9);
        cbcaltype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Non-customer", "Customer-Driver", "Customer-User", "Customer-PIC", "Customer-Other", "Internal-ANJ", "Internal-CC", "Internal-CSO", "Internal-Driver", "Internal-Other" }));
        jPanel2.add(cbcaltype);
        cbcaltype.setBounds(110, 80, 200, 24);

        jLabel16.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel16.setText("Cust. Company");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(10, 110, 100, 0);

        cbcust.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        cbcust.setMaximumRowCount(9);
        cbcust.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Non-customer", "Customer-Driver", "Customer-User", "Customer-PIC", "Customer-Other", "Internal-ANJ", "Internal-CC", "Internal-CSO", "Internal-Driver", "Internal-Other" }));
        jPanel2.add(cbcust);
        cbcust.setBounds(110, 110, 200, 0);

        btnmute.setFont(btnmute.getFont().deriveFont(btnmute.getFont().getStyle() | java.awt.Font.BOLD, 11));
        btnmute.setForeground(new java.awt.Color(0, 102, 102));
        btnmute.setText("Mute");
        btnmute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmuteActionPerformed(evt);
            }
        });
        jPanel2.add(btnmute);
        btnmute.setBounds(220, 470, 90, 20);

        ckHold.setFont(ckHold.getFont().deriveFont((float)11));
        ckHold.setText("Hold");
        ckHold.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        ckHold.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        ckHold.setOpaque(false);
        ckHold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckHoldActionPerformed(evt);
            }
        });
        jPanel2.add(ckHold);
        ckHold.setBounds(160, 470, 60, 20);

        cksugges.setBackground(new java.awt.Color(255, 255, 255));
        cksugges.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        cksugges.setText("*OTHERS");
        cksugges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cksuggesActionPerformed(evt);
            }
        });
        jPanel2.add(cksugges);
        cksugges.setBounds(10, 170, 100, 20);

        ckinqui1.setBackground(new java.awt.Color(255, 255, 255));
        ckinqui1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        ckinqui1.setText("*REQUEST");
        ckinqui1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckinqui1ActionPerformed(evt);
            }
        });
        jPanel2.add(ckinqui1);
        ckinqui1.setBounds(10, 130, 100, 20);

        jLabel13.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel13.setText("*Caller Type :");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(20, 80, 90, 20);

        cbsendertype.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        cbsendertype.setMaximumRowCount(9);
        jPanel2.add(cbsendertype);
        cbsendertype.setBounds(110, 80, 200, 0);

        cbInq.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        cbInq.setEnabled(false);
        jPanel2.add(cbInq);
        cbInq.setBounds(110, 110, 200, 24);

        cbInqTr.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        cbInqTr.setEnabled(false);
        jPanel2.add(cbInqTr);
        cbInqTr.setBounds(110, 130, 200, 24);

        cbComp.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        cbComp.setEnabled(false);
        jPanel2.add(cbComp);
        cbComp.setBounds(110, 150, 200, 24);

        cbSugges.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        cbSugges.setEnabled(false);
        jPanel2.add(cbSugges);
        cbSugges.setBounds(110, 170, 200, 24);

        txtnotic1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jPanel2.add(txtnotic1);
        txtnotic1.setBounds(110, 220, 200, 24);

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel5.setText("No Pelanggan");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 220, 90, 20);

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel6.setText("Others Phone");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(20, 240, 90, 20);

        txtnotic2.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jPanel2.add(txtnotic2);
        txtnotic2.setBounds(110, 240, 200, 24);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 330, 500);

        txtlogid.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        txtlogid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlogidActionPerformed(evt);
            }
        });
        getContentPane().add(txtlogid);
        txtlogid.setBounds(10, 770, 199, 20);

        txtlogid1.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        getContentPane().add(txtlogid1);
        txtlogid1.setBounds(80, 770, 199, 20);

        txtlogid2.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        getContentPane().add(txtlogid2);
        txtlogid2.setBounds(80, 770, 199, 20);

        txtlogid3.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        getContentPane().add(txtlogid3);
        txtlogid3.setBounds(80, 770, 199, 20);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Contact"));
        jPanel4.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jPanel4.setLayout(null);

        tbltic.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        tbltic.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbltic.setRowHeight(18);
        tbltic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblticMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbltic);

        jPanel4.add(jScrollPane3);
        jScrollPane3.setBounds(20, 30, 650, 180);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(330, 270, 690, 230);
        jPanel4.getAccessibleContext().setAccessibleName("Distributor");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Call History"));
        jPanel1.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jPanel1.setLayout(null);

        btnsrch.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnsrch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/1245117595_001_37.png"))); // NOI18N
        btnsrch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsrchActionPerformed(evt);
            }
        });
        jPanel1.add(btnsrch);
        btnsrch.setBounds(640, 30, 24, 24);

        jScrollPane1.setAutoscrolls(true);

        tblcall.setAutoCreateRowSorter(true);
        tblcall.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        tblcall.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblcall.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblcall.setDoubleBuffered(true);
        tblcall.setFillsViewportHeight(true);
        tblcall.setRowHeight(18);
        tblcall.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblcallMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblcall);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 50, 650, 200);

        jLabel23.setBackground(new java.awt.Color(102, 102, 255));
        jLabel23.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel23.setText(" Id :"); // NOI18N
        jPanel1.add(jLabel23);
        jLabel23.setBounds(400, 30, 140, 0);

        txtIdCust.setEditable(false);
        txtIdCust.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtIdCust.setEnabled(false);
        jPanel1.add(txtIdCust);
        txtIdCust.setBounds(500, 30, 140, 0);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(330, 0, 690, 270);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnopenticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnopenticActionPerformed
        // TODO add your handling code here:
        cccs_ticket tic=new cccs_ticket();
        tic.setVisible(true);

        Tic.newtic=true;
        Tic.txtCusNam.setText(txtcalnm.getText());
        Tic.txtCusPho.setText(txtcalnum.getText());
        Tic.txtdetails.setText(txtareacom.getText());
}//GEN-LAST:event_btnopenticActionPerformed

    private void btnexpandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexpandActionPerformed
        // TODO add your handling code here:
//        if (sco==0){
//            this.setSize(1025,470);
//            sco++;
//        }else{
//            this.setSize(332,470);
//            sco=0;
//        }
}//GEN-LAST:event_btnexpandActionPerformed

    private void btnsaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsaveMouseClicked
        // TODO add your handling code here:
//        if(cbcust.getSelectedIndex()!=-1){
            String notic=txtnotic.getText();
            condition="";
            if(notic!=null){
                notic="'"+notic+"'";
            }
            acwstop();
            if(ckwrongno.isSelected()==true){
                wrongnum=1;
            }else{
                wrongnum=0;
            }
            if(ckcompl.isSelected()==true){
                complaint=1;
                if(cbComp.getSelectedIndex()!=-1)
                    condition=condition+", _complaint_detail='"+cbComp.getSelectedItem()+"'";
                else
                    condition=condition+", _complaint_detail=null";
            }else{
                complaint=0;
            }
            if(ckinqui.isSelected()==true){
                inquiry=1;
                if(cbInq.getSelectedIndex()!=-1)
                    condition=condition+", _inquiry_detail='"+cbInq.getSelectedItem()+"'";
                else
                    condition=condition+", _inquiry_detail=null";
            }else{
                inquiry=0;
            }
            if(ckinqui1.isSelected()==true){
                inqtrans=1;
                if(cbInqTr.getSelectedIndex()!=-1)
                    condition=condition+", _inquirytransfer_detail='"+cbInqTr.getSelectedItem()+"'";
                else
                    condition=condition+", _inquirytransfer_detail=null";
            }else{
                inqtrans=0;
            }
            if (ckblank.isSelected()==true){
                blankcall=1;
            }else{
                blankcall=0;
            }
            if (cksugges.isSelected()==true){
                suggest=1;
                if(cbSugges.getSelectedIndex()!=-1)
                    condition=condition+", _suggestion_detail='"+cbSugges.getSelectedItem()+"'";
                else
                    condition=condition+", _suggestion_detail=null";
            }else{
                suggest=0;
            }
            if (txtnotic.getText().equals("")){
                notic=null;
            }
            if(blankcall==0){
                 if(txtcalnum.getText().equals("")||txtcalnm.getText().equals("")){
                    JOptionPane.showMessageDialog(null,"Data Incomplete, Please fill Caller Name first");
                }else{
//                     System.out.print("d dalem save \n"+loid);
                     if(CCanj.inshow==true){
    //                     sql="update log_phone set duration='"+lbldurasi.getText()+"', busy='"+busy+"', _inquiry='"+inquiry+"', _complaint='"+complaint+"', caller_number='"+txtcalnum.getText()+"', caller_type='"+cbcaltype.getSelectedItem()+"', caller_name='"+txtcalnm.getText()+"', comment='"+txtareacom.getText()+"', ticket_id='"+notic+"', _callback='"+callback+"', callback_time='"+cldt+" "+txtcalbac.getText()+"', _wrongnumber='"+wrongnum+"' where log_id='"+loid+"'";
                         sql="update log_phone set _suggestion='"+suggest+"', _inquirytransfer='"+inqtrans+"', _inquiry='"+inquiry+"', _complaint='"+complaint+"'"
                                 + ", caller_number='"+txtcalnum.getText()+"', caller_type='"+cbcaltype.getSelectedItem()+"', comment='"+txtareacom.getText()+"'"
                                 + ", ticket_no="+notic+", ticket_id=(select ticket_id from tickets where ticket_no="+notic+")"
                                 + ", _wrongnumber='"+wrongnum+"'"
                                 + ", cust_name='"+txtnotic2.getText()+"'"
                                 + ", bikepoint_id='"+txtnotic1.getText()+"'";
                         sql=sql+condition+ " where log_id='"+loid+"'";
                         CCanj.jconn.SQLExecute(sql, CCanj.conn);
    //                     System.out.print("update click 2x \n"+sql);
//                         JOptionPane.showMessageDialog(null,"Data successfully updated");
                         xxx=0;
                         inqtrans=0;suggest=0;blankcall=0;inquiry=0;complaint=0;wrongnum=0;
                         dispose();
                     }else{
    //                     if (callback==1 || (!clbk.equals(null)) || (!txtcalbac.getText().equals(""))){
    //                         sql="update log_phone set duration='"+lbldurasi.getText()+"', busy='"+busy+"', _inquiry='"+inquiry+"', _complaint='"+complaint+"', caller_number='"+txtcalnum.getText()+"', caller_type='"+cbcaltype.getSelectedItem()+"', caller_name='"+txtcalnm.getText()+"', comment='"+txtareacom.getText()+"', ticket_id='"+notic+"', _callback='"+callback+"', callback_time='"+cldt+" "+txtcalbac.getText()+"', _wrongnumber='"+wrongnum+"' where log_id='"+loid+"'";
                             sql="update log_phone set duration='"+lbldurasi.getText()+"', _suggestion='"+suggest+"', _inquirytransfer='"+inqtrans+"', _inquiry='"+inquiry+"', _complaint='"+complaint+"'"
                                     + ", caller_number='"+txtcalnum.getText()+"', caller_type='"+cbcaltype.getSelectedItem()+"', caller_name='"+txtcalnm.getText()+"', comment='"+txtareacom.getText()+"'"
                                     + ", ticket_no="+notic+", ticket_id=(select ticket_id from tickets where ticket_no="+notic+")"
                                     + ", _wrongnumber='"+wrongnum+"'"
                                     + ", cust_name='"+txtnotic2.getText()+"'"
                                     + ", bikepoint_id='"+txtnotic1.getText()+"'";
                             sql=sql+condition+ " where log_id='"+CCanj.loid+"'";
                             CCanj.jconn.SQLExecute(sql, CCanj.conn);
//                            JOptionPane.showMessageDialog(null,"Data successfully updated");
                            xxx=0;
                             inqtrans=0;suggest=0;blankcall=0;inquiry=0;complaint=0;wrongnum=0;
                            if (hangup==false){
//                                JOptionPane.showMessageDialog(null,"Hang Up the phone first");
                            }else{
                                dispose();
                            }
    //                     }else{
    //                         JOptionPane.showMessageDialog(null,"Data Incomplete, Please fill Date and time first");
    //                     }
                     }
                }
            }else{
                if(CCanj.inshow==true){
    //                sql="update log_phone set _blankcall=1, duration='"+lbldurasi.getText()+"', busy='"+busy+"', _inquiry='"+inquiry+"', _complaint='"+complaint+"', caller_number='"+txtcalnum.getText()+"', caller_type='"+cbcaltype.getSelectedItem()+"', caller_name='"+txtcalnm.getText()+"', comment='"+txtareacom.getText()+"', ticket_id='"+notic+"', _callback='"+callback+"', callback_time='"+cldt+" "+txtcalbac.getText()+"' where log_id='"+CCanj.loid+"'";
                    sql="update log_phone set _blankcall=1, _suggestion='"+suggest+"', _inquirytransfer='"+inqtrans+"', _inquiry='"+inquiry+"', _complaint='"+complaint+"'"
                            + ", caller_number='"+txtcalnum.getText()+"', caller_type='"+cbcaltype.getSelectedItem()+"', comment='"+txtareacom.getText()+"'"
                            + ", ticket_no="+notic+", ticket_id=(select ticket_id from tickets where ticket_no="+notic+")"
                            + ", cust_name='"+txtnotic2.getText()+"'"
                            + ", bikepoint_id='"+txtnotic1.getText()+"'";
                    sql=sql+condition+ " where log_id='"+loid+"'";
                    CCanj.jconn.SQLExecute(sql, CCanj.conn);
//                    System.out.print(sql);
//                    JOptionPane.showMessageDialog(null,"Data successfully updated");
                    xxx=0;
                    inqtrans=0;suggest=0;blankcall=0;inquiry=0;complaint=0;wrongnum=0;
                    dispose();
                }else{
                    sql="update log_phone set _blankcall=1, _suggestion='"+suggest+"', duration='"+lbldurasi.getText()+"', _inquirytransfer='"+inqtrans+"', _inquiry='"+inquiry+"', _complaint='"+complaint+"'"
                            + ", caller_number='"+txtcalnum.getText()+"', caller_type='"+cbcaltype.getSelectedItem()+"', caller_name='"+txtcalnm.getText()+"', comment='"+txtareacom.getText()+"'"
                            + ", ticket_no="+notic+", ticket_id=(select ticket_id from tickets where ticket_no="+notic+")"
                            + ", cust_name='"+txtnotic2.getText()+"'"
                            + ", bikepoint_id='"+txtnotic1.getText()+"'";
                    sql=sql+condition+ " where log_id='"+CCanj.loid+"'";
                    CCanj.jconn.SQLExecute(sql, CCanj.conn);
//                    System.out.print(sql);
//                    JOptionPane.showMessageDialog(null,"Data successfully updated");
                    xxx=0;
                    inqtrans=0;suggest=0;blankcall=0;inquiry=0;complaint=0;wrongnum=0;                    
                    if (hangup==false){
//                        JOptionPane.showMessageDialog(null,"Hang Up the phone first");
                    }else{
                        dispose();
                    }
                }
            }
//        }else{
//            JOptionPane.showMessageDialog(null, "Please input the Customer Company");
//        }
    }//GEN-LAST:event_btnsaveMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        CCanj.inshow=false;
        if (xx==1){
            dataregis();
            xx=0;
            String S;
            acwstop();
            ab.stop();
            sql="update log_phone set busy='"+busy+"' where log_id='"+loid+"'";
             CCanj.jconn.SQLExecute(sql, CCanj.conn);
            int i=JOptionPane.showConfirmDialog(null, "Ready to receive next Inbound Call ? [YES]\nReady to do Outbound Call ? [NO]","Exit",JOptionPane.YES_NO_OPTION);
            if (i==JOptionPane.YES_OPTION){
                CCanj.s = "REGISTER|"+pabx+"|"+in_ext+"|"+in_ext+"\r\n";
                CCanj.kirimTele();
                CCanj.lblactivity.setText("Registered");
//                System.out.print("registerulang");
                sql1="update user_account set _activity=4, info='INBOUND' ,time_activity=CURRENT_TIMESTAMP where username= '" +CCanj.lbluser.getText()+ "' limit 1";
                CCanj.jconn.SQLExecute(sql1,CCanj.conn);
            }else{
//                CCanj.btnready.setText("Ready");
//                CCanj.btncall.setEnabled(false);
//                CCanj.btnsms.setEnabled(false);
//                CCanj.btnmail.setEnabled(false);
//                CCanj.btnfax.setEnabled(false);
//                CCanj.cbdirection.setEnabled(true);
//                CCanj.btnlogout.setEnabled(true);
//                CCanj.s = "UNREGISTER|"+pabx+"|"+in_ext+"|"+in_ext+"\r\n";
//                CCanj.kirimTele();
//                CCanj.lblactivity.setText("Disconnected");
//                CCanj.counter=0;
                CCanj.lblactivity.setText("Registered");
                CCanj.cbdirection.setSelectedIndex(1);
                sql1="update user_account set _activity=4, info='OUTBOUND' ,time_activity=CURRENT_TIMESTAMP where username= '" +CCanj.lbluser.getText()+ "' limit 1";
                CCanj.jconn.SQLExecute(sql1,CCanj.conn);
            }
        }
        CCanj.tabelin();
//        try {
//            conn.close();
//        } catch (SQLException ex) {
//            System.err.println(ex.getMessage());
//        }
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        if(xxx==0){
            if (hangup==false){
                JOptionPane.showMessageDialog(null,"Hang Up the phone first");
            }else{
                dispose();
            }
        }else{
            if (hangup==false){
                JOptionPane.showMessageDialog(null,"Hang Up the phone first");
            }else{
                JOptionPane.showMessageDialog(null,"Data Incomplete, Please fill Date and time first");
            }
        }
    }//GEN-LAST:event_formWindowClosing

    private void tblticMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblticMouseClicked
        // TODO add your handling code here:
        if(tabticconf.getRowCount()!=0){
//            if(evt.getClickCount()==2){
//                txtareacom.setText(txtareacom.getText()+"\n\n"
//                        + ""+(String)tbltic.getValueAt(tbltic.getSelectedRow(),tbltic.getTableHeader().getColumnModel().getColumnIndex("Ticket No.")));
//            }else if(evt.getClickCount()==1){
//                cccs_History hic = new cccs_History();
//                hic.setVisible(true);
//
//                Hic.no=ticid;
//                Hic.ticid=Integer.valueOf((String)txtnotic.getText());
//                Hic.klik2();
//            }
        }
}//GEN-LAST:event_tblticMouseClicked
  
        
    private void tblcallMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblcallMouseClicked
        // TODO add your handling code here:
        if(tabcall.getRowCount()!=0){
            if(evt.getClickCount()==1){
                txtIdCust.setText((String)tblcall.getValueAt(tblcall.getSelectedRow(),tblcall.getTableHeader().getColumnModel().getColumnIndex("Id")));
                IdCust=(String)tblcall.getValueAt(tblcall.getSelectedRow(),tblcall.getTableHeader().getColumnModel().getColumnIndex("Id"));
//                tabelcall();tabeltic();
            }
        }
}//GEN-LAST:event_tblcallMouseClicked

    private void btnsrchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsrchActionPerformed
        // TODO add your handling code here:
//        cccs_Search_customer srcus= new cccs_Search_customer();
//        srcus.setVisible(true);
//        
//        srcus.Form=2;
//        srcus.txtPhoneNo.setText(txtcalnum.getText());  
//        srcus.txtOwner.setText(txtcalnm.getText());  
//        srcus.tabelcus();
//        srcus.tabeltic();
        tabelticconf();
}//GEN-LAST:event_btnsrchActionPerformed

    private void ckblankMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ckblankMouseClicked
        // TODO add your handling code here:
        if (ckblank.isSelected()==true){
            blankcall=1;
            ckinqui.setEnabled(false);
            ckcompl.setEnabled(false);
            ckinqui1.setEnabled(false);
            cksugges.setEnabled(false);
        }else{
            blankcall=0;
            ckinqui.setEnabled(true);
            ckcompl.setEnabled(true);
            ckinqui1.setEnabled(true);
            cksugges.setEnabled(true);
        }
    }//GEN-LAST:event_ckblankMouseClicked

    private void btnHangUpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHangUpMouseEntered
        // TODO add your handling code here:
        if(txtcalnm.getText().equals("")){
            
        }
    }//GEN-LAST:event_btnHangUpMouseEntered
boolean mute=false;
    private void btnHangUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHangUpActionPerformed
        // TODO add your handling code here:
//        if(){
            if(!txtcalnm.getText().equals("")){
                String tgl=CCanj.lt.replace(':','.');
                String notic=txtnotic.getText();
    //            String nmfl="[JSM] "+opdt+" IN "+CCanj.lbluser.getText()+" "+tgl+" "+txtcalnm.getText()+".wav";
                String nmfl=""+CCanj.ld+" [DIST ORANGE TV] IN "+CCanj.lbluser.getText()+" "+tgl+" "+txtcalnm.getText()+" "+txtcalnum.getText()+".wav";

                stop();
                ti.stop();
                CCanj.s = "HANGUP|"+nmfl+"|"+CCanj.ld+" "+CCanj.lt+"\r\n";
                CCanj.kirimTele();
                s=null;
                JOptionPane.showMessageDialog(null, "CALL DISCONNECTED", "INCOMING CALL",JOptionPane.WARNING_MESSAGE);
                if (txtnotic.getText().equals("")){
                    notic=null;
                }
                sql="update log_phone set duration='"+lbldurasi.getText()+"',_suggestion='"+suggest+"', _inquirytransfer='"+inqtrans+"', _inquiry='"+inquiry+"', _complaint='"+complaint+"', caller_number='"+txtcalnum.getText()+"', caller_type='"+cbcaltype.getSelectedItem()+"', caller_name='"+txtcalnm.getText()+"', comment='"+txtareacom.getText()+"', filename='"+nmfl+"'"
                        + ", cust_name='"+txtnotic2.getText()+"'"
                        + ", bikepoint_id='"+txtnotic1.getText()+"'"
                        + " where log_id='"+loid+"'";
                CCanj.jconn.SQLExecute(sql, CCanj.conn);
                acwstart();
                try {
                    Thread.sleep(500);
                } catch (InterruptedException ex) {
                    Logger.getLogger(cccs_InBoundCall.class.getName()).log(Level.SEVERE, null, ex);
                }
    //            s = "UPLOAD|RECORDING|"+nmfl+"|192.168.0.32|anj\r\n";
                CCanj.s = "UPLOAD|RECORDING|"+nmfl+"|"+Log.ftpserverRec+"|"+Log.ftpuserRec+"\r\n";
                CCanj.kirimUplo();
                JOptionPane.showMessageDialog(null, "RECORDING "+nmfl+" Has been uploaded", "INBOUND CALL",JOptionPane.WARNING_MESSAGE);
                //                  System.out.print(s);
                hangup=true;
                acwstart();
                ab.start();
                CCanj.lblactivity.setText("Disconnected");
                btnHangUp.setEnabled(false);
            }else{
                JOptionPane.showMessageDialog(null, "Caller Name cannot be empty", "INCOMING CALL",JOptionPane.WARNING_MESSAGE);
            }
//        }
    }//GEN-LAST:event_btnHangUpActionPerformed

    private void txtlogidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlogidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlogidActionPerformed

    private void btnmuteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmuteActionPerformed
        // TODO add your handling code here:
        if(mute==false){
            ckHold.setEnabled(false);
            if(ckHold.isSelected()==true){
                btnmute.setText("Unhold");
                CCanj.s = "HOLD\r\n";
            }else{
                btnmute.setText("Unmute");
                CCanj.s = "MUTE\r\n";
            }
            btnmute.setForeground(Color.red);
            CCanj.kirimTele();
            mute=true;
        }else{
            ckHold.setEnabled(true);
            if(ckHold.isSelected()==true){
                btnmute.setText("Hold");
                CCanj.s = "UNHOLD\r\n";
            }else{
                btnmute.setText("Mute");
                CCanj.s = "UNMUTE\r\n";
            }
            btnmute.setForeground(Color.black);
            CCanj.kirimTele();
            mute=false;
        }
}//GEN-LAST:event_btnmuteActionPerformed

    private void ckHoldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckHoldActionPerformed
        // TODO add your handling code here:
        if(ckHold.isSelected()==true){
            btnmute.setText("Hold");
        }else{
            btnmute.setText("Mute");
        }
}//GEN-LAST:event_ckHoldActionPerformed

    private void ckinquiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckinquiActionPerformed
        // TODO add your handling code here:
        if(ckinqui.isSelected()==true){
            inquiry=1;
            cbInq.setEnabled(true);
        }else{
            inquiry=0;
            cbInq.setEnabled(false);
            cbInq.setSelectedIndex(-1);
        }
    }//GEN-LAST:event_ckinquiActionPerformed

    private void ckblankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckblankActionPerformed
        // TODO add your handling code here:
        if (ckblank.isSelected()==true){
            blankcall=1;
        }else{
            blankcall=0;
        }
    }//GEN-LAST:event_ckblankActionPerformed

    private void cksuggesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cksuggesActionPerformed
        // TODO add your handling code here:
        if (cksugges.isSelected()==true){
            suggest=1;
            cbSugges.setEnabled(true);
        }else{
            suggest=0;
            cbSugges.setEnabled(false);
            cbSugges.setSelectedIndex(-1);
        }
    }//GEN-LAST:event_cksuggesActionPerformed

    private void ckwrongnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckwrongnoActionPerformed
        // TODO add your handling code here:
        if(ckwrongno.isSelected()==true){
            wrongnum=1;
        }else{
            wrongnum=0;
        }
    }//GEN-LAST:event_ckwrongnoActionPerformed

    private void ckinqui1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckinqui1ActionPerformed
        // TODO add your handling code here:
        if(ckinqui1.isSelected()==true){
            inqtrans=1;
            cbInqTr.setEnabled(true);
        }else{
            inqtrans=0;
            cbInqTr.setEnabled(false);
            cbInqTr.setSelectedIndex(-1);
        }
    }//GEN-LAST:event_ckinqui1ActionPerformed

    private void ckcomplActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckcomplActionPerformed
        // TODO add your handling code here:
        if(ckcompl.isSelected()==true){
            complaint=1;
            cbComp.setEnabled(true);
        }else{
            complaint=0;
            cbComp.setEnabled(false);
            cbComp.setSelectedIndex(-1);
        }
    }//GEN-LAST:event_ckcomplActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        // TODO add your handling code here:
        txtnotic.setText("");
        ticid=0;
    }//GEN-LAST:event_btnresetActionPerformed

    private void btnsaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsaveMouseEntered
        // TODO add your handling code here:
        if(txtcalnm.getText().equals("")||cbcaltype.getSelectedIndex()==-1||txtareacom.getText().length()<=5||(ckcompl.isSelected()==false&&ckinqui.isSelected()==false&&ckinqui1.isSelected()==false&&cksugges.isSelected()==false)){
//            if(ckcompl.isSelected()==false&&ckinqui.isSelected()==false&&ckinqui1.isSelected()==false&&cksugges.isSelected()==false){
                JOptionPane.showMessageDialog(null,"Fill Al mandatory Field\nWhich has stars mark(*)");
//            }
        }
    }//GEN-LAST:event_btnsaveMouseEntered

    public static javax.swing.table.DefaultTableModel getDefaultTabelticconf(){
        return new javax.swing.table.DefaultTableModel(
                new Object [][]{},
                new String [] {"KODE","Dealer","Alamat","Kota/Kabupaten","Kode Pos"       ,"Propinsi","Contact Person","No Telp/HP","Fax"}){
                boolean[] canEdit=new boolean[]{
                    false,false,false,false,false       ,false,false,false,false
                };
                public boolean isCellEditable(int rowIndex, int columnIndex){
                        return canEdit[columnIndex];
                }
        };
    }    
    public static javax.swing.table.DefaultTableModel tabticconf=getDefaultTabelticconf();
    
    private void tabelticconf(){
        tabticconf.setRowCount(0);
             try{
                 sql="select * "
                         + " from contact "
                         + " where contact_id is not null "
                         + " and dealer like '%"+txtcalnm.getText()+"%' "
                         + " and contact_person like '%"+txtcalnm.getText()+"%' "
                         + " and no_tlp like '%"+txtcalnum.getText()+"%' ";
                 condition="";
                 sql=sql+condition+" order by dealer";
              rs=CCanj.jconn.SQLExecuteRS(sql, CCanj.conn);

            while(rs.next()){
                tic[0]=rs.getString(2);
                tic[1]=rs.getString(3);
                tic[2]=rs.getString(4);
                tic[3]=rs.getString(5);
                tic[4]=rs.getString(6);
                tic[5]=rs.getString(7);
                tic[6]=rs.getString(8);
                tic[7]=rs.getString(9);
                tic[8]=rs.getString(10);
                tabticconf.addRow(tic);
            }
        }catch(Exception exc){
            System.err.println(exc.getMessage());
        }
    }    

    public static javax.swing.table.DefaultTableModel getDefaultCallHist(){
        return new javax.swing.table.DefaultTableModel(
                new Object [][]{},
                new String [] {"Media","Direction","Date","Time","Username"     ,"Status","Type","Caller Name","Comment","Ticket No"
                        ,"Id"}){
                boolean[] canEdit=new boolean[]{
                    false,false,false,false,false,false     ,false,false,false,false,false
                        ,false
                };
                public boolean isCellEditable(int rowIndex, int columnIndex){
                        return canEdit[columnIndex];
                }
        };
    }    
    public static javax.swing.table.DefaultTableModel tabcall=getDefaultCallHist();
    public static void tabelcall(){
        tabcall.setRowCount(0);
        try{
            x=0;
            sql="select 'Call' as Media, _direction.data as Direction"
                    + ", log_date as 'Date', log_time as 'Time'"
                    + ", username, _callstatus.data as stt"
                    + ", caller_type as 'Type', caller_name"
                    + ", comment as 'note', ifnull(log_phone.ticket_no,tickets.ticket_no) as ticket"
                    + ", log_phone.bikepoint_id"
                    + " from log_phone "
                    + " join _direction on log_phone._direction=_direction.code"
                    + " left join _callstatus on log_phone._callstatus=_callstatus.code"
                    + " left join tickets on log_phone.ticket_id=tickets.ticket_id"
                    + " where caller_number like '%"+txtcalnum.getText()+"%' or phone_number like '%"+txtcalnum.getText()+"%' or log_phone.bikepoint_id="+IdCust+""
                    + " UNION"
                    + " select 'SMS' as Media, _direction.data as Direction"
                    + ", sms_date, sms_time"
                    + ", username"
                    + ", case _direction"
                    + "  when 0 then rcvd_status.data "
                    + "  when 1 then send_status.data "
                    + "  end as stt"
                    + ", direction_type as 'Type', ''"
                    + ", log_sms.bikepoint_id"
                    + ", sms_text as 'note', ifnull(log_sms.ticket_no,tickets.ticket_no) as ticket"
                    + " from log_sms"
                    + " join _direction on log_sms._direction=_direction.code"
                    + " join rcvd_status on log_sms._status=rcvd_status.code"
                    + " join send_status on log_sms._status=send_status.code"
                    + " left join tickets on log_sms.ticket_id=tickets.ticket_id"
                    + " where sms_to like '%"+txtcalnum.getText()+"%' or sms_from like '%"+txtcalnum.getText()+"%' or log_sms.bikepoint_id="+IdCust+"";            
            rs=CCanj.jconn.SQLExecuteRS(sql, CCanj.conn);
//              System.out.println(sql);

            while(rs.next()){
                cus[x]=rs.getString("Media");x++;
                cus[x]=rs.getString("Direction");x++;
                cus[x]=rs.getString("Date");x++;
                cus[x]=rs.getString("Time");x++;
                cus[x]=rs.getString("username");x++;

                cus[x]=rs.getString("stt");x++;
                cus[x]=rs.getString("Type");x++;
                cus[x]=rs.getString("caller_name");x++;
                cus[x]=rs.getString("note");x++;
                cus[x]=rs.getString("ticket");x++;

                cus[x]=rs.getString("bikepoint_id");x++;
                tabcall.addRow(cus);
                x=0;
            }
        }catch(Exception exc){
            System.err.println(exc.getMessage());
        }
    }

    private void tbcus(javax.swing.JTable tb, int lebar[]){
        tb.setAutoResizeMode(tb.AUTO_RESIZE_OFF);
        int kolom=tb.getColumnCount();
        for (int i=0;i<kolom;i++){
            javax.swing.table.TableColumn tbc=tb.getColumnModel().getColumn(i);
            tbc.setPreferredWidth(lebar[i]);
            tb.setRowHeight(17);
        }
    }
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cccs_InBoundCall().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnHangUp;
    private javax.swing.JButton btnexpand;
    private javax.swing.JButton btnmute;
    private javax.swing.JButton btnopentic;
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnsrch;
    public static javax.swing.JComboBox cbComp;
    public static javax.swing.JComboBox cbInq;
    public static javax.swing.JComboBox cbInqTr;
    public static javax.swing.JComboBox cbSugges;
    public static javax.swing.JComboBox cbcaltype;
    public static javax.swing.JComboBox cbcust;
    public static javax.swing.JComboBox cbsendertype;
    private javax.swing.JCheckBox ckHold;
    public static javax.swing.JCheckBox ckblank;
    public static javax.swing.JCheckBox ckcompl;
    public static javax.swing.JCheckBox ckinqui;
    public static javax.swing.JCheckBox ckinqui1;
    public static javax.swing.JCheckBox cksugges;
    public static javax.swing.JCheckBox ckwrongno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public static javax.swing.JLabel lbldurasi;
    private javax.swing.JTable tblcall;
    private javax.swing.JTable tbltic;
    public static javax.swing.JTextField txtIdCust;
    public static javax.swing.JTextArea txtareacom;
    public static javax.swing.JTextField txtcalnm;
    public static javax.swing.JTextField txtcalnum;
    public static javax.swing.JTextField txtlogid;
    public static javax.swing.JTextField txtlogid1;
    public static javax.swing.JTextField txtlogid2;
    public static javax.swing.JTextField txtlogid3;
    public static javax.swing.JTextField txtnotic;
    public static javax.swing.JTextField txtnotic1;
    public static javax.swing.JTextField txtnotic2;
    // End of variables declaration//GEN-END:variables


    public static String sql;
    private String sql1, sqlid;
    public static ResultSet rs;
    public static long startTime = 0;
    public static long stopTime = 0;
    public static long acwstartTime = 0;
    public static long acwstopTime = 0;
    public static boolean running = false;


    public static void cek(){
        try{
            if(hangup==true){
                sql="select * from log_phone where log_id='"+loid+"'";
                rs=CCanj.jconn.SQLExecuteRS(sql, CCanj.conn);
                while(rs.next()){
                    txtcalnm.setText(rs.getString("caller_name"));
                    txtcalnum.setText(rs.getString("caller_number"));
                    cbcaltype.setSelectedItem(rs.getString("caller_type"));

                    txtnotic.setText(rs.getString("ticket_no"));
                    txtareacom.setText(rs.getString("comment"));
                    lbldurasi.setText(rs.getString("duration"));
                    blankcall=Integer.parseInt(rs.getString("_blankcall"));
                    suggest=Integer.parseInt(rs.getString("_suggestion"));
                    complaint=Integer.parseInt(rs.getString("_complaint"));
                    inquiry=Integer.parseInt(rs.getString("_inquiry"));
                    inqtrans=Integer.parseInt(rs.getString("_inquirytransfer"));
                    wrongnum=Integer.parseInt(rs.getString("_wrongnumber"));
                    cbInq.setSelectedItem(rs.getString("_inquiry_detail"));
                    cbInqTr.setSelectedItem(rs.getString("_inquirytransfer_detail"));
                    cbComp.setSelectedItem(rs.getString("_complaint_detail"));
                    cbSugges.setSelectedItem(rs.getString("_suggestion_detail"));
                }
                if(wrongnum==1){
                    ckwrongno.setSelected(true);
                }
                if(complaint==1){
                    ckcompl.setSelected(true);
                    cbComp.setEnabled(true);
                }
                if(inquiry==1){
                    ckinqui.setSelected(true);
                    cbInq.setEnabled(true);
                }
                if(suggest==1){
                    cksugges.setSelected(true);
                    cbSugges.setEnabled(true);
                }
                if(inqtrans==1){
                    ckinqui1.setSelected(true);
                    cbInqTr.setEnabled(true);
                }
                if (blankcall==1){
                    ckblank.setSelected(true);
                    cksugges.setEnabled(true);
                    ckinqui.setEnabled(false);
                    ckinqui1.setEnabled(false);
                    ckcompl.setEnabled(false);
                }
            }else{
                if (lbldurasi.getText().equals("")){
                     System.out.print("Proses cek durasi");
                    start();
                     System.out.print("start timer");
                    ti= new Timer(1000, duration);
                    ti.start();
                    xx=1;
                    xxx=1;
                    btnHangUp.setEnabled(true);
                }
            }
        }catch(Exception exc){
            System.err.println(exc.getMessage());
        }
    }
    
    
    
    public void dataregis(){
        try{
            int row=0;
            sql="select pabx_host, inbound_ext, outbound_ext from user_account where username='"+CCanj.lbluser.getText()+"'";
            rs=CCanj.jconn.SQLExecuteRS(sql, CCanj.conn);
//              System.out.println(sql);
            while(rs.next()){
                pabx=rs.getString(1);
                in_ext=rs.getString(2);
                out_ext=rs.getString(3);
            }
        }catch(Exception exc){
            System.err.println(exc.getMessage());
        }
    }        
      
    public static void start() {
        cccs_InBoundCall.startTime = System.currentTimeMillis();
    }


    public static void stop() {
        cccs_InBoundCall.stopTime = System.currentTimeMillis();
    }


    //elaspsed time in seconds
    public static long duration() {
        if (running) {
            elapsed = ((stopTime - startTime) / 1000);
        }
        else {
            elapsed = ((System.currentTimeMillis() - startTime) / 1000);

                long hours = elapsed / 3600,
                remainder = elapsed % 3600,
                minutes = remainder / 60,
                seconds = remainder % 60;

                String ho=(hours<10 ? "0" : "")+hours,
                menit=(minutes<10 ? "0" : "")+minutes,
                detik=(seconds<10 ? "0" : "")+seconds;
        lbldurasi.setText(ho+":"+menit+":"+detik);
        }
        return elapsed;
    }

    public static Action duration = new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                duration();
            }
       };

    public static void acwstart() {
        cccs_InBoundCall.acwstartTime = System.currentTimeMillis();
    }


    public static void acwstop() {
        cccs_InBoundCall.acwstopTime = System.currentTimeMillis();
    }

    public static long acw() {
        if (running) {
            busy = ((acwstopTime - acwstartTime) / 1000);
        }
        else {
            busy = ((System.currentTimeMillis() - acwstartTime) / 1000);
        }
        return busy;
    }

    public static Action acw = new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                acw();
            }
       };
    private void ambilTgl(){
        GregorianCalendar now=new GregorianCalendar();
        int tgl=now.get(now.DATE);
        int bln=now.get(now.MONTH)+1;
        int thn=now.get(now.YEAR);
        int h=now.get(now.HOUR);
        int m=now.get(now.MINUTE);
        int s=now.get(now.SECOND);

//    txtcalbac.setText(String.valueOf(h)+String.valueOf(m)+String.valueOf(s));
    }
    String optm, opdt;
    
    private void optm(){
          try{
              sql="select CURRENT_TIME";
              rs = CCanj.jconn.SQLExecuteRS(sql, CCanj.conn);
              while(rs.next()){
                  optm=rs.getString(1);
              }
//            txtcalbac.setText(optm);
          }catch(Exception exc){
              System.err.println(exc.getMessage());
          }
    }
    private void opdt(){
          try{
              sql="select CURRENT_DATE";
              rs = CCanj.jconn.SQLExecuteRS(sql, CCanj.conn);
              while(rs.next()){
                  opdt=rs.getString(1);
              }
          }catch(Exception exc){
              System.err.println(exc.getMessage());
          }
    }
    private void showCaltype(){
        try{
            cbcaltype.removeAllItems();

            sql="select data from _callertype";
            rs=CCanj.jconn.SQLExecuteRS(sql,CCanj.conn);
            while(rs.next()){
                cbcaltype.addItem(rs.getString(1));
            }
        }catch(Exception e){
            System.out.println(e);

        }
    }
    private void showCust(){
        try{
            cbcust.removeAllItems();
            cbcust.addItem("Others");

            sql="select distinct(cust_name) from customer_order order by cust_name";
            rs=CCanj.jconn.SQLExecuteRS(sql,CCanj.conn);
            while(rs.next()){
                cbcust.addItem(rs.getString(1));
            }
            cbcust.setSelectedIndex(-1);
        }catch(Exception e){
            System.out.println(e);

        }
    }
    private void showCat1(){
          cbInq.removeAllItems();
          try{
              sql="select data from _inquiry";
              rs=CCanj.jconn.SQLExecuteRS(sql,CCanj.conn);
              while(rs.next()){
                  cbInq.addItem(rs.getString(1));
              }
              cbInq.setSelectedIndex(-1);
          }catch(Exception e){
              System.out.println(e);
          }
      }
    private void showCat2(){
          cbComp.removeAllItems();
          try{
              sql="select data from _complaint";
              rs=CCanj.jconn.SQLExecuteRS(sql,CCanj.conn);
              while(rs.next()){
                  cbComp.addItem(rs.getString(1));
              }
              cbComp.setSelectedIndex(-1);
          }catch(Exception e){
              System.out.println(e);
          }
    }
    private void showCat3(){
          cbInqTr.removeAllItems();
          try{
              sql="select data from _request";
              rs=CCanj.jconn.SQLExecuteRS(sql,CCanj.conn);
              while(rs.next()){
                  cbInqTr.addItem(rs.getString(1));
              }
              cbInqTr.setSelectedIndex(-1);
          }catch(Exception e){
              System.out.println(e);
          }
    }
    private void showCat4(){
          cbSugges.removeAllItems();
          try{
              sql="select data from _other";
              rs=CCanj.jconn.SQLExecuteRS(sql,CCanj.conn);
              while(rs.next()){
                  cbSugges.addItem(rs.getString(1));
              }
              cbSugges.setSelectedIndex(-1);
          }catch(Exception e){
              System.out.println(e);
          }
    }
}