/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * cccs_Closed_tic.java
 *
 * Created on Mar 15, 2010, 1:04:46 PM
 */

package cc_orangetv;

import javax.sun.database.JavaConnector;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author jsm
 */
public class cccs_Closed_tic extends javax.swing.JFrame {

    public static int conf=1;
    /** Creates new form cccs_Closed_tic */
    public cccs_Closed_tic() {
        initComponents();
    }

    private ContactCenterOrangeTv CCanj;
    public cccs_Closed_tic(ContactCenterOrangeTv ccanj){
        this();
        this.CCanj=ccanj;
    }
    private cccs_ticket Tic;
    public cccs_Closed_tic(cccs_ticket tic){
        this();
        this.Tic=tic;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel9 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtsolution = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("TICKET CLOSING");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel9.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jPanel9.setLayout(null);

        jButton1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jButton1.setText("Closed Ticket");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton1);
        jButton1.setBounds(10, 220, 105, 24);

        jButton2.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jButton2.setText("Cancel");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel9.add(jButton2);
        jButton2.setBounds(300, 220, 100, 24);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jPanel3.setLayout(null);

        txtsolution.setColumns(20);
        txtsolution.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtsolution.setLineWrap(true);
        txtsolution.setRows(5);
        jScrollPane4.setViewportView(txtsolution);

        jPanel3.add(jScrollPane4);
        jScrollPane4.setBounds(10, 20, 380, 150);

        jPanel9.add(jPanel3);
        jPanel3.setBounds(10, 40, 400, 180);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        Tic.usrlvl();
        sql="update tickets set _status=3, close_date=CURRENT_DATE, close_time=CURRENT_TIME, close_username='"+CCanj.lbluser.getText()+"', solution='"+txtsolution.getText()+"' where ticket_id='"+Tic.id+"'";
        CCanj.jconn.SQLExecute(sql,CCanj.conn);
        sql1="insert into log_tickets (log_date,log_time,username,user_level,ticket_id,info,ticket_no,_status) values (CURRENT_DATE,CURRENT_TIME,'"+CCanj.lbluser.getText()+"','"+Tic.usrlvl+"','"+Tic.id+"','"+txtsolution.getText()+"','"+Tic.txtnotic.getText()+"',3)";
        CCanj.jconn.SQLExecute(sql1,CCanj.conn);
//        sql1="insert into log_mail (mail_date,mail_time,mail_from,mail_to,mail_subject,mail_text,ticket_id,direction,username)"
//                + " values"
//                + " (CURRENT_DATE,CURRENT_TIME,'customercare@polytron.co.id','"+Tic.txtPicMail.getText()+"','<notify>#"+Tic.txtCusNam.getText()+"#"+Tic.cbcategory.getSelectedItem()+"#"+Tic.txtnotic.getText()+"','CLOSED by : "+CCanj.lbluser.getText()+"\n"+opdt+"\n"+optm+"\n\nDetails :\n"+Tic.txtdetails.getText()+"\n\nSoluiton :\n"+Tic.txtlastnote.getText()+"','"+Tic.id+"',1,'"+CCanj.lbluser.getText()+")";
//        CCanj.jconn.SQLExecute(sql1,CCanj.conn);
        JOptionPane.showMessageDialog(null, "TICKET HAS BEEN CLOSED", "TICKETING",JOptionPane.WARNING_MESSAGE);
        dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2MouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
//        try {
//            conn.close();
//        } catch (SQLException ex) {
//            System.err.println(ex.getMessage());
//        }
    }//GEN-LAST:event_formWindowClosed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cccs_Closed_tic().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane4;
    public static javax.swing.JTextArea txtsolution;
    // End of variables declaration//GEN-END:variables

    public static String sql;
    public static String sql1;
    public static ResultSet rs;
    public static String opdt;
    public static String optm;

    
}
