/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * cccs_OutBound.java
 *
 * Created on Feb 23, 2010, 11:03:52 PM
 */

package cc_orangetv;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.Timer;
import java.awt.*;
import java.awt.Event.*;
import java.awt.event.ActionEvent;
import java.sql.*;
import javax.sun.database.JavaConnector;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import java.io.*;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.PrintWriter;
import java.util.Calendar;
import java.util.Iterator;
import java.util.List;
import java.util.ArrayList;
import java.net.*;
/**
 *
 * @author jsm
 */
public class cccs_OutBound extends javax.swing.JFrame {

    public static int z;
    public static String zz, IdCust=null;
    public static int oid=0;
    public static Timer ti;

    public static String loid;
    public static int conf;
    private static boolean running=false;
    private static boolean call=false;
    public static boolean obtic=false;
    private static long elapsed;
    private static long startTime=0;
    private static long stopTime=0;
    private static int submit;
    private static String optm;
    private static String opdt;

    private String pabx;
    private String in_ext;
    private String out_ext;
    public static int xxx=0;
    private String usrlvl;
     public static int status;
    public static int asdep;
    private String solution;
    /** Creates new form cccs_OutBound */
    public cccs_OutBound() {
        initComponents();
        usrlvl();
        showCaltype(); 
        setSize(335,565);
        setLocation(10,10);
//        showCust();
    }

    private cccs_login Log;
    public cccs_OutBound(cccs_login log){
        this();
        this.Log=log;
    }
    public static ContactCenterOrangeTv CCanj;
    public cccs_OutBound(ContactCenterOrangeTv ccanj){
        this();
        this.CCanj=ccanj;
    }
    private cccs_ticket Tic;
    public cccs_OutBound(cccs_ticket tic){
        this();
        this.Tic=tic;
    }
    public cccs_Search_ticket Sct;
    public cccs_OutBound(cccs_Search_ticket sct){
        this();
        this.Sct=sct;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtdialnm = new javax.swing.JTextField();
        txtdial = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnhangup = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtcomment = new javax.swing.JTextArea();
        btncall = new javax.swing.JButton();
        txtnotic1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        btnclose = new javax.swing.JButton();
        btnsrchcus = new javax.swing.JButton();
        cbcaltype = new javax.swing.JComboBox();
        ckconf = new javax.swing.JCheckBox();
        btnsave = new javax.swing.JButton();
        lbldurasi = new javax.swing.JLabel();
        btnopentic = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        txtdial2 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        cbcust = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtdetails = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtsolution = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtnotic = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbcategory = new javax.swing.JComboBox();
        cbprior = new javax.swing.JComboBox();
        cbdept = new javax.swing.JComboBox();
        tabdet = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        txtGuarantyNo = new javax.swing.JTextField();
        txtCusNam = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtcusfax = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtCusPho = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtcustadd = new javax.swing.JTextArea();
        jLabel24 = new javax.swing.JLabel();
        txtIdCust = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtPicHp = new javax.swing.JTextField();
        txtPicPho = new javax.swing.JTextField();
        txtPic = new javax.swing.JTextField();
        txtPicMail = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        txtPicAdd = new javax.swing.JTextArea();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        cbTicketType = new javax.swing.JComboBox();
        jLabel56 = new javax.swing.JLabel();
        cbTicketSource = new javax.swing.JComboBox();
        jLabel59 = new javax.swing.JLabel();
        cbProduct = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        cbBussLine = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("OUTBOUND CALL");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "OutBound Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 12))); // NOI18N
        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 204));
        jLabel1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel1.setText("Call Number");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 30, 100, 20);

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel2.setText("Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 70, 100, 20);

        txtdialnm.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtdialnm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtdialnmFocusLost(evt);
            }
        });
        jPanel1.add(txtdialnm);
        txtdialnm.setBounds(110, 70, 200, 24);

        txtdial.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jPanel1.add(txtdial);
        txtdial.setBounds(110, 30, 150, 24);

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel3.setText("Caller Type");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 90, 100, 20);

        btnhangup.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnhangup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/4.jpg"))); // NOI18N
        btnhangup.setText("Hang UP");
        btnhangup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnhangupMouseClicked(evt);
            }
        });
        btnhangup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhangupActionPerformed(evt);
            }
        });
        jPanel1.add(btnhangup);
        btnhangup.setBounds(171, 460, 140, 24);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "comment", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 12))); // NOI18N

        txtcomment.setColumns(20);
        txtcomment.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtcomment.setLineWrap(true);
        txtcomment.setRows(5);
        jScrollPane2.setViewportView(txtcomment);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(9, 170, 300, 280);

        btncall.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btncall.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/3.jpg"))); // NOI18N
        btncall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncallActionPerformed(evt);
            }
        });
        jPanel1.add(btncall);
        btncall.setBounds(260, 30, 50, 39);

        txtnotic1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtnotic1.setAutoscrolls(false);
        txtnotic1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtnotic1MouseClicked(evt);
            }
        });
        txtnotic1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnotic1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtnotic1);
        txtnotic1.setBounds(110, 100, 100, 0);

        jLabel20.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel20.setText("Ticket Id.");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(10, 100, 100, 0);

        btnclose.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnclose.setText("Close");
        btnclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncloseMouseClicked(evt);
            }
        });
        jPanel1.add(btnclose);
        btnclose.setBounds(10, 460, 80, 24);

        btnsrchcus.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        btnsrchcus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/1245117595_001_37.png"))); // NOI18N
        btnsrchcus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsrchcusMouseClicked(evt);
            }
        });
        btnsrchcus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsrchcusActionPerformed(evt);
            }
        });
        jPanel1.add(btnsrchcus);
        btnsrchcus.setBounds(210, 100, 20, 0);

        cbcaltype.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        cbcaltype.setMaximumRowCount(9);
        cbcaltype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Non-customer", "Customer-Driver", "Customer-User", "Customer-PIC", "Customer-Other", "Internal-ANJ", "Internal-CC", "Internal-CSO", "Internal-Driver", "Internal-Other" }));
        cbcaltype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbcaltypeActionPerformed(evt);
            }
        });
        jPanel1.add(cbcaltype);
        cbcaltype.setBounds(110, 90, 200, 24);

        ckconf.setBackground(new java.awt.Color(204, 204, 255));
        ckconf.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        ckconf.setText("Confirmed");
        ckconf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ckconfMouseClicked(evt);
            }
        });
        jPanel1.add(ckconf);
        ckconf.setBounds(110, 120, 100, 0);

        btnsave.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnsave.setText("Save");
        btnsave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsaveMouseClicked(evt);
            }
        });
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnsave);
        btnsave.setBounds(90, 460, 80, 24);

        lbldurasi.setFont(lbldurasi.getFont().deriveFont(lbldurasi.getFont().getStyle() | java.awt.Font.BOLD, 11));
        lbldurasi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbldurasi.setToolTipText("");
        jPanel1.add(lbldurasi);
        lbldurasi.setBounds(170, 480, 140, 20);

        btnopentic.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnopentic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/tic.jpg"))); // NOI18N
        btnopentic.setText("Open Ticket");
        btnopentic.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnopentic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnopenticActionPerformed(evt);
            }
        });
        jPanel1.add(btnopentic);
        btnopentic.setBounds(160, 164, 150, 0);

        jLabel37.setBackground(new java.awt.Color(255, 255, 204));
        jLabel37.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel37.setText("Ext.");
        jPanel1.add(jLabel37);
        jLabel37.setBounds(10, 50, 100, 20);

        txtdial2.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtdial2.setEnabled(false);
        txtdial2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdial2KeyReleased(evt);
            }
        });
        jPanel1.add(txtdial2);
        txtdial2.setBounds(110, 50, 150, 24);

        jLabel36.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel36.setText("Cust. Company");
        jPanel1.add(jLabel36);
        jLabel36.setBounds(10, 110, 100, 0);

        cbcust.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        cbcust.setMaximumRowCount(9);
        cbcust.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Non-customer", "Customer-Driver", "Customer-User", "Customer-PIC", "Customer-Other", "Internal-ANJ", "Internal-CC", "Internal-CSO", "Internal-Driver", "Internal-Other" }));
        jPanel1.add(cbcust);
        cbcust.setBounds(110, 110, 200, 0);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 329, 560);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 12))); // NOI18N
        jPanel2.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jPanel2.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel8.setText("Details :"); // NOI18N
        jPanel2.add(jLabel8);
        jLabel8.setBounds(20, 10, 100, 20);

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel9.setText("Solution :"); // NOI18N
        jPanel2.add(jLabel9);
        jLabel9.setBounds(20, 80, 100, 20);

        txtdetails.setColumns(20);
        txtdetails.setEditable(false);
        txtdetails.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtdetails.setLineWrap(true);
        txtdetails.setRows(5);
        jScrollPane1.setViewportView(txtdetails);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(120, 10, 380, 60);

        txtsolution.setColumns(20);
        txtsolution.setEditable(false);
        txtsolution.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtsolution.setLineWrap(true);
        txtsolution.setRows(5);
        jScrollPane8.setViewportView(txtsolution);

        jPanel2.add(jScrollPane8);
        jScrollPane8.setBounds(120, 80, 380, 60);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(330, 390, 510, 170);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "<<TICKET REFERENCE>>", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 12))); // NOI18N
        jPanel4.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        jPanel4.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Ticket No. :"); // NOI18N
        jPanel4.add(jLabel4);
        jLabel4.setBounds(260, 20, 80, 20);

        txtnotic.setEditable(false);
        txtnotic.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtnotic.setEnabled(false);
        jPanel4.add(txtnotic);
        txtnotic.setBounds(340, 20, 140, 24);

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel5.setText("*Category :"); // NOI18N
        jPanel4.add(jLabel5);
        jLabel5.setBounds(20, 100, 100, 20);

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel6.setText("  Prority :"); // NOI18N
        jPanel4.add(jLabel6);
        jLabel6.setBounds(20, 20, 100, 20);

        cbcategory.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jPanel4.add(cbcategory);
        cbcategory.setBounds(120, 100, 300, 24);

        cbprior.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        cbprior.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NORMAL", "URGENT" }));
        jPanel4.add(cbprior);
        cbprior.setBounds(120, 20, 140, 24);

        cbdept.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jPanel4.add(cbdept);
        cbdept.setBounds(120, 80, 360, 24);

        tabdet.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel5.setLayout(null);

        jLabel23.setBackground(new java.awt.Color(102, 102, 255));
        jLabel23.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel23.setText(" Id :"); // NOI18N
        jPanel5.add(jLabel23);
        jLabel23.setBounds(10, 10, 100, 20);

        txtGuarantyNo.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jPanel5.add(txtGuarantyNo);
        txtGuarantyNo.setBounds(110, 30, 360, 24);

        txtCusNam.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jPanel5.add(txtCusNam);
        txtCusNam.setBounds(110, 50, 360, 24);

        jLabel7.setBackground(new java.awt.Color(102, 102, 255));
        jLabel7.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel7.setText("*Cust. Name :"); // NOI18N
        jPanel5.add(jLabel7);
        jLabel7.setBounds(4, 50, 100, 20);

        jLabel10.setBackground(new java.awt.Color(102, 102, 255));
        jLabel10.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Cust.Fax :"); // NOI18N
        jPanel5.add(jLabel10);
        jLabel10.setBounds(240, 70, 100, 20);

        txtcusfax.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jPanel5.add(txtcusfax);
        txtcusfax.setBounds(340, 70, 130, 24);

        jLabel11.setBackground(new java.awt.Color(102, 102, 255));
        jLabel11.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel11.setText("Cust. Phone :"); // NOI18N
        jPanel5.add(jLabel11);
        jLabel11.setBounds(10, 70, 100, 20);

        txtCusPho.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jPanel5.add(txtCusPho);
        txtCusPho.setBounds(110, 70, 130, 24);

        jLabel21.setBackground(new java.awt.Color(102, 102, 255));
        jLabel21.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel21.setText("Cust address:"); // NOI18N
        jPanel5.add(jLabel21);
        jLabel21.setBounds(10, 90, 100, 20);

        txtcustadd.setColumns(20);
        txtcustadd.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtcustadd.setLineWrap(true);
        txtcustadd.setRows(5);
        jScrollPane6.setViewportView(txtcustadd);

        jPanel5.add(jScrollPane6);
        jScrollPane6.setBounds(110, 90, 360, 60);

        jLabel24.setBackground(new java.awt.Color(102, 102, 255));
        jLabel24.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel24.setText(" Bike Point Name :"); // NOI18N
        jPanel5.add(jLabel24);
        jLabel24.setBounds(10, 30, 100, 20);

        txtIdCust.setEditable(false);
        txtIdCust.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtIdCust.setEnabled(false);
        jPanel5.add(txtIdCust);
        txtIdCust.setBounds(110, 10, 140, 24);

        tabdet.addTab("Customer", jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel6.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel13.setText("Cordinator :"); // NOI18N
        jPanel6.add(jLabel13);
        jLabel13.setBounds(10, 10, 100, 20);

        jLabel14.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel14.setText("Phone :"); // NOI18N
        jPanel6.add(jLabel14);
        jLabel14.setBounds(10, 30, 100, 20);

        jLabel22.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel22.setText("Email :"); // NOI18N
        jPanel6.add(jLabel22);
        jLabel22.setBounds(10, 70, 100, 20);

        txtPicHp.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jPanel6.add(txtPicHp);
        txtPicHp.setBounds(110, 50, 360, 24);

        txtPicPho.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jPanel6.add(txtPicPho);
        txtPicPho.setBounds(110, 30, 360, 24);

        txtPic.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jPanel6.add(txtPic);
        txtPic.setBounds(110, 10, 360, 24);

        txtPicMail.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jPanel6.add(txtPicMail);
        txtPicMail.setBounds(110, 70, 360, 24);

        jLabel57.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel57.setText("Address :"); // NOI18N
        jPanel6.add(jLabel57);
        jLabel57.setBounds(10, 90, 100, 20);

        jLabel58.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel58.setText("Handphone :"); // NOI18N
        jPanel6.add(jLabel58);
        jLabel58.setBounds(10, 50, 100, 20);

        txtPicAdd.setColumns(20);
        txtPicAdd.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtPicAdd.setLineWrap(true);
        txtPicAdd.setRows(5);
        jScrollPane12.setViewportView(txtPicAdd);

        jPanel6.add(jScrollPane12);
        jScrollPane12.setBounds(110, 90, 360, 60);

        tabdet.addTab("PIC", jPanel6);

        jPanel4.add(tabdet);
        tabdet.setBounds(10, 160, 492, 210);

        jLabel54.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel54.setText("*Department :"); // NOI18N
        jPanel4.add(jLabel54);
        jLabel54.setBounds(20, 80, 100, 20);

        jLabel55.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel55.setText("*Product :"); // NOI18N
        jPanel4.add(jLabel55);
        jLabel55.setBounds(20, 60, 100, 20);

        cbTicketType.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jPanel4.add(cbTicketType);
        cbTicketType.setBounds(340, 40, 140, 24);

        jLabel56.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel56.setText(" *Ticket type :"); // NOI18N
        jPanel4.add(jLabel56);
        jLabel56.setBounds(260, 40, 80, 20);

        cbTicketSource.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jPanel4.add(cbTicketSource);
        cbTicketSource.setBounds(120, 40, 140, 24);

        jLabel59.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel59.setText("*Ticket Source :"); // NOI18N
        jPanel4.add(jLabel59);
        jLabel59.setBounds(20, 40, 100, 20);

        cbProduct.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jPanel4.add(cbProduct);
        cbProduct.setBounds(120, 60, 360, 24);

        jLabel12.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel12.setText("  Bussiness Line :"); // NOI18N
        jPanel4.add(jLabel12);
        jLabel12.setBounds(20, 120, 100, 20);

        cbBussLine.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        cbBussLine.setEnabled(false);
        jPanel4.add(cbBussLine);
        cbBussLine.setBounds(120, 120, 360, 24);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(330, 0, 510, 390);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncloseMouseClicked
        // TODO add your handling code here:
        if(xxx==0){
            dispose();
        }else{
            JOptionPane.showMessageDialog(null,"Data Incomplete, Please fill Date and time first");
        }
}//GEN-LAST:event_btncloseMouseClicked

    private void btnsrchcusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsrchcusMouseClicked
        // TODO add your handling code here:
        cccs_Search_ticket st = new cccs_Search_ticket();
        st.setVisible(true);
        Sct.out=true;
}//GEN-LAST:event_btnsrchcusMouseClicked

    private void txtnotic1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnotic1MouseClicked
        // TODO add your handling code here:
        try{
           sql="select a.ticket_no, a._priority, a.category, b.dept_name, a.assign_dept, a.user, a.user_phone, a.vehicle_platno, a.vehicle_type, a.vehicle_warna, a.driver_name, a.driver_phone, a.cust_name, a.cust_phone, a.cust_pic, a.cust_pic_phone, a.cso_name, a.cso_phone, a.details, a.solution from tickets a, _department b where a.dept_id=b.dept_id and a.ticket_id='"+txtnotic1.getText()+"' ";
            rs=CCanj.jconn.SQLExecuteRS(sql,CCanj.conn);
            while(rs.next()){
                txtnotic.setText(rs.getString(1));
                cbcategory.addItem(rs.getString(3));
                cbprior.setSelectedIndex(Integer.parseInt(rs.getString(2)));
                cbdept.addItem(rs.getString(4));
                txtdetails.setText(rs.getString(19));
//                txtsolution.setText(rs.getString(12));
//                txtsolutionclos.setText(rs.getString(12));
            }
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_txtnotic1MouseClicked

    private void btnhangupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhangupMouseClicked
        // TODO add your handling code here:
       
}//GEN-LAST:event_btnhangupMouseClicked

    private void txtnotic1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnotic1ActionPerformed
        // TODO add your handling code here:
        if (txtnotic1.getText().equals("")){
            
        }else{
            klik2();
        }
    }//GEN-LAST:event_txtnotic1ActionPerformed

    private void btnsaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsaveMouseClicked
        // TODO add your handling code here:
        if(call==true){
            zz=loid;
        }
//        if(txtnotic1.getText().equals("")){
//            JOptionPane.showMessageDialog(null, "Ticket No cannot be empty", "VALIDATION",JOptionPane.WARNING_MESSAGE);
//        }else{
            if(ckconf.isSelected()==true){
                conf=2;
            }else{
                conf=1;
            }
            if(cbcaltype.getSelectedIndex()!=-1){
                sql = "update log_phone set"
                        + " comment='"+txtcomment.getText()+"' "
                        + ", caller_type='"+cbcaltype.getSelectedItem()+"'"
                        + ", ticket_id='"+oid+"' , ticket_no='"+txtnotic.getText()+"' "
//                        + ", bikepoint_id="+IdCust+" "
                        + " where log_id='"+loid+"'";
                CCanj.jconn.SQLExecute(sql, CCanj.conn);
            }else{
                JOptionPane.showMessageDialog(null, "Please input the Caller Type");
            }
//        }
        
        
}//GEN-LAST:event_btnsaveMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        stt();
        if(call==true){
            if(obtic==true){
                if (status==0 && asdep==0){
                    sql="update tickets set _status=1, process_date='"+opdt+"', process_time='"+optm+"', process_username='"+CCanj.lbluser.getText()+"' where ticket_id='"+Tic.id+"' and ticket_no='"+txtnotic.getText()+"'";
                    CCanj.jconn.SQLExecute(sql,CCanj.conn);
                    System.out.print(sql);
                    status=1;
                }
                sql1="insert into log_tickets (log_date,log_time,username,user_level,ticket_id,_status,info,ticket_no) values ('"+opdt+"','"+optm+"','"+CCanj.lbluser.getText()+"','"+usrlvl+"','"+txtnotic1.getText()+"','"+status+"','Outgoing Call \nDial Number : "+txtdial.getText()+"\nDial Name : "+txtdialnm.getText()+"\nCaller type : "+cbcaltype.getSelectedItem()+" \n\n "+txtcomment.getText()+"','"+txtnotic.getText()+"')";
                CCanj.jconn.SQLExecute(sql1, CCanj.conn);
                try{
                    sql2="select note from tickets where ticket_id='"+Tic.id+"'";
                    rs = CCanj.jconn.SQLExecuteRS(sql2, CCanj.conn);
                    while(rs.next()){
                        solution=rs.getString(1);
                    }
                }catch(Exception exc){
                    System.err.println(exc.getMessage());
                }
                sql3="update tickets set note='"+CCanj.lbluser.getText()+"@"+opdt.substring(8, 10) + "/" + opdt.substring(5, 7) + "/" + opdt.substring(0, 4)+"\n"+optm.replaceAll(":",".")+"\nOutgoing Call \nDial Number : "+txtdial.getText()+"\nDial Name : "+txtdialnm.getText()+"\nCaller type : "+cbcaltype.getSelectedItem()+" \n\n "+txtcomment.getText()+"\n===' where ticket_id='"+Tic.id+"'";
                CCanj.jconn.SQLExecute(sql3,CCanj.conn);
            }
            zz=loid;
        }        
        if(ckconf.isSelected()==true){
                conf=2;
            }else{
                conf=1;
            }

            if(zz==null){
                sql = "update tickets set " +
                        "confirmed='"+conf+"' " +
                        "where ticket_id='"+oid+"'";
                CCanj.jconn.SQLExecute(sql, CCanj.conn);

            }else{
                sql = "update tickets set " +
                    "confirmed='"+conf+"' " +
                    ", logphone_id='"+zz+"' " +
                    "where ticket_id='"+oid+"'";
                CCanj.jconn.SQLExecute(sql, CCanj.conn);
//                JOptionPane.showMessageDialog(null, "UPDATE, TICKET HAS CONFIRMED ", "TICKETING",JOptionPane.WARNING_MESSAGE);
            }
        CCanj.call();
        call=false;
        btncall.setEnabled(true);
//        try {
//            conn.close();
//        } catch (SQLException ex) {
//            System.err.println(ex.getMessage());
//        }
    }//GEN-LAST:event_formWindowClosed

    private void ckconfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ckconfMouseClicked
        // TODO add your handling code here:
         if(ckconf.isSelected()==true){
                conf=2;
            }else{
                conf=1;
            }
    }//GEN-LAST:event_ckconfMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        System.out.print(xxx);
        if(xxx==0){
            dispose();
        }else{
            JOptionPane.showMessageDialog(null,"Data Incomplete, Please fill Date and time first");
        }
    }//GEN-LAST:event_formWindowClosing

    private void txtdialnmFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtdialnmFocusLost
        // TODO add your handling code here:
        if(!txtdialnm.getText().equals("")){
            btnhangup.setEnabled(true);
        }
    }//GEN-LAST:event_txtdialnmFocusLost

    private void btnopenticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnopenticActionPerformed
        // TODO add your handling code here:
        cccs_ticket tic=new cccs_ticket();
        tic.setVisible(true);

        Tic.caltic=true;
        Tic.newtic=true;
}//GEN-LAST:event_btnopenticActionPerformed

    private void cbcaltypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbcaltypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbcaltypeActionPerformed

    private void btnhangupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhangupActionPerformed
        // TODO add your handling code here:
        if(!txtdialnm.getText().equals("")){
        String tgl=optm.replace(':','.');
        String notic=txtnotic.getText();
        String nmfl=""+opdt+" [DIST ORANGE TV] OUT "+CCanj.lbluser.getText()+" "+tgl+" "+txtdialnm.getText()+" "+txtdial.getText()+".wav";
//        String nmfl="[JSM] "+opdt+" OUT "+CCanj.lbluser.getText()+" "+tgl+" "+txtdialnm.getText()+".wav";

        ti.stop();
            CCanj.s = "HANGUP|"+nmfl+"|"+opdt+" "+optm+"\r\n";
            CCanj.kirimTele();
            sql="update log_phone set caller_name='"+txtdialnm.getText()+"', ticket_id='"+txtnotic1.getText()+"', ticket_no='"+txtnotic.getText()+"', caller_type='"+cbcaltype.getSelectedItem()+"', comment='"+txtcomment.getText()+"', duration='"+lbldurasi.getText()+"', filename='"+nmfl+"' where log_id='"+loid+"'";
            CCanj.jconn.SQLExecute(sql, CCanj.conn);
            JOptionPane.showMessageDialog(null, "CALL DISCONNECTED", "OUTGOING CALL",JOptionPane.WARNING_MESSAGE);

            try {
                Thread.sleep(1000);
            } catch (InterruptedException ex) {
                Logger.getLogger(cccs_InBoundCall.class.getName()).log(Level.SEVERE, null, ex);
            }
                  CCanj.s = "UPLOAD|RECORDING|"+nmfl+"|"+Log.ftpserverRec+"|"+Log.ftpuserRec+"\r\n";
                  CCanj.kirimUplo();
                  xxx=0;
//                  System.out.print(xxx);
                  JOptionPane.showMessageDialog(null, "OUTBOUND RECORDING "+nmfl+" Has been uploaded", "OUTGOING CALL",JOptionPane.WARNING_MESSAGE);
                  CCanj.lblactivity.setText("Registered");
                  btnhangup.setEnabled(false);
        }else{
            JOptionPane.showMessageDialog(null, "Call Name cannot be empty", "INCOMING CALL",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnhangupActionPerformed

    private void btncallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncallActionPerformed
        // TODO add your handling code here:
        dataregis();
        optm();
        opdt();
        cek();
        CCanj.s = "REGISTER|"+pabx+"|"+out_ext+"|"+out_ext+"\r\n";
        CCanj.kirimTele();
        try {
            Thread.sleep(1000);
        } catch (InterruptedException ex) {
            Logger.getLogger(cccs_OutBound.class.getName()).log(Level.SEVERE, null, ex);
        }
        String prefix="9";
//        if(txtdial.getText().substring(0,3).equals("021")){
//            prefix="6";
//        }else if(txtdial.getText().substring(0,4).equals("0856")||txtdial.getText().substring(0,4).equals("0815")||txtdial.getText().substring(0,4).equals("0816")||txtdial.getText().substring(0,4).equals("0857")){
//            prefix="9";
//        }else if(txtdial.getText().substring(0,4).equals("0812")||txtdial.getText().substring(0,4).equals("0811")||txtdial.getText().substring(0,4).equals("0852")||txtdial.getText().substring(0,4).equals("0813")){
//            prefix="7";
//        }else if(txtdial.getText().substring(0,4).equals("0817")||txtdial.getText().substring(0,4).equals("0818")||txtdial.getText().substring(0,4).equals("0878")){
//            prefix="8";
//        }
        CCanj.s = "DIAL|"+prefix+txtdial.getText()+"\r\n";
        CCanj.kirimTele();
        JOptionPane.showMessageDialog(null, "CALLING \n"+txtdial.getText(), "OUTGOING CALL",JOptionPane.WARNING_MESSAGE);
        sql="insert into log_phone (log_date,log_time,username,shift,host_addr,line_number,_direction,phone_number"
                + ",ticket_id, ticket_no , bikepoint_id)"
                + " values"
                + " ('"+opdt+"','"+optm+"','"+CCanj.lbluser.getText()+"','"+Log.cbshift.getSelectedIndex()+"','"+Log.hostadd+"','"+out_ext+"',1,'"+txtdial.getText()+"'"
                + ",'"+txtnotic1.getText()+"','"+txtnotic.getText()+"',"+IdCust+")";
        CCanj.jconn.SQLExecute(sql, CCanj.conn);

                      sqlid="select distinct last_insert_id() from log_phone";
                      rs=CCanj.jconn.SQLExecuteRS(sqlid, CCanj.conn);
                        try {
                            while (rs.next()) {
                                loid = rs.getString(1);
                            }
                        } catch (SQLException ex) {
                            Logger.getLogger(cccs_OutBound.class.getName()).log(Level.SEVERE, null, ex);
                        }
        call=true;
        CCanj.lblactivity.setText("On line");
        sql3="update user_account set _activity=3, time_activity=CURRENT_TIMESTAMP where username= '" +CCanj.lbluser.getText()+ "' limit 1";
        CCanj.jconn.SQLExecute(sql3, CCanj.conn);
        btncall.setEnabled(false);
        txtdial2.setEnabled(true);
    }//GEN-LAST:event_btncallActionPerformed
String digit,s,ext,delete;
int d,index,last,del;
    private void txtdial2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdial2KeyReleased
        // TODO add your handling code here:
        try {
            Thread.sleep(500);
        } catch (InterruptedException ex) {
            Logger.getLogger(cccs_OutBound.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (evt.getKeyChar()>=48 && evt.getKeyChar()<=57 || evt.getKeyChar()==8){
            ext=","+txtdial2.getText();
            d=ext.length();
            digit=ext.substring(d-1, d);
            if(d>=2 && evt.getKeyChar()!=8){
                CCanj.s = "DTMF|"+digit+"\r\n";
                CCanj.kirimTele();
            }
        }else{
            ext=","+txtdial2.getText();
            del=ext.length();
            if (del>=1){
                ext=ext.substring(1,del-1);
                txtdial2.setText(ext);
            }
            JOptionPane.showMessageDialog(null, "Character Number Only", "validation",JOptionPane.WARNING_MESSAGE);
        }
}//GEN-LAST:event_txtdial2KeyReleased

    private void btnsrchcusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsrchcusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsrchcusActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnsaveActionPerformed

           
    
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
       java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cccs_OutBound().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncall;
    private javax.swing.JButton btnclose;
    public static javax.swing.JButton btnhangup;
    private javax.swing.JButton btnopentic;
    public static javax.swing.JButton btnsave;
    private javax.swing.JButton btnsrchcus;
    public static javax.swing.JComboBox cbBussLine;
    public static javax.swing.JComboBox cbProduct;
    public static javax.swing.JComboBox cbTicketSource;
    public static javax.swing.JComboBox cbTicketType;
    public static javax.swing.JComboBox cbcaltype;
    public static javax.swing.JComboBox cbcategory;
    public static javax.swing.JComboBox cbcust;
    public static javax.swing.JComboBox cbdept;
    public static javax.swing.JComboBox cbprior;
    public static javax.swing.JCheckBox ckconf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane8;
    public static javax.swing.JLabel lbldurasi;
    public static javax.swing.JTabbedPane tabdet;
    public static javax.swing.JTextField txtCusNam;
    public static javax.swing.JTextField txtCusPho;
    public static javax.swing.JTextField txtGuarantyNo;
    public static javax.swing.JTextField txtIdCust;
    public static javax.swing.JTextField txtPic;
    public static javax.swing.JTextArea txtPicAdd;
    public static javax.swing.JTextField txtPicHp;
    public static javax.swing.JTextField txtPicMail;
    public static javax.swing.JTextField txtPicPho;
    public static javax.swing.JTextArea txtcomment;
    public static javax.swing.JTextField txtcusfax;
    public static javax.swing.JTextArea txtcustadd;
    public static javax.swing.JTextArea txtdetails;
    public static javax.swing.JTextField txtdial;
    public static javax.swing.JTextField txtdial2;
    public static javax.swing.JTextField txtdialnm;
    public static javax.swing.JTextField txtnotic;
    public static javax.swing.JTextField txtnotic1;
    public static javax.swing.JTextArea txtsolution;
    // End of variables declaration//GEN-END:variables

    public static String sql;
    public static String sql1;
    public static String sql2;
    public static String sql3;
    public static String sqlid;
    public static ResultSet rs;
//    public static JavaConnector jconn=new JavaConnector();
//    public static Connection conn;

    public static void cek(){

         if (lbldurasi.getText().equals("")){
             System.out.print("Proses cek durasi");
            start();
             System.out.print("start timer");
            ti= new Timer(1000, duration);
            ti.start();
            xxx=1;

        }
    }
       
        private void opdt(){
          try{
              sql="select CURRENT_DATE";
              rs = CCanj.jconn.SQLExecuteRS(sql, CCanj.conn);
              while(rs.next()){
                  opdt=rs.getString(1);
              }
          }catch(Exception exc){
              System.err.println(exc.getMessage());
          }
    }
        private void optm(){
            try{
              sql="select CURRENT_TIME";
              rs = CCanj.jconn.SQLExecuteRS(sql, CCanj.conn);
              while(rs.next()){
                  optm=rs.getString(1);
              }
          }catch(Exception exc){
              System.err.println(exc.getMessage());
          }
        }
        public static void klik2(){
            try{
            sql="select tickets.*, _department.dept_name"
                    + ", _bussinesline.data as bsl"
                    + ", c.data as src"
                    + " from tickets"
                    + " join _department on tickets.dept_id=_department.dept_id"
                    + " join _bussinesline d on tickets.bussiness_line_id=d.code"
                    + " join _callertype c on tickets.source_id=c.code"
                    + " where ticket_no='"+txtnotic.getText()+"' ";
            rs=CCanj.jconn.SQLExecuteRS(sql,CCanj.conn);

//                 System.out.println(sql);
            while(rs.next()){
                txtnotic1.setText(rs.getString("ticket_id"));
                oid=Integer.parseInt(rs.getString("ticket_id"));
                cbcategory.addItem(rs.getString("category"));
                    cbTicketType.addItem(rs.getString("_type"));
                    cbprior.setSelectedIndex(Integer.parseInt(rs.getString("_priority")));
                    cbdept.addItem(rs.getString("dept_name"));
                    cbProduct.addItem(rs.getString("product"));
                    cbTicketSource.addItem(rs.getString("src"));
                    cbBussLine.addItem(rs.getString("bsl"));
                    txtIdCust.setText(rs.getString("bikepoint_id"));
                    IdCust=(rs.getString("bikepoint_id"));
                    txtGuarantyNo.setText(rs.getString("bikepoint_name"));
                    txtCusNam.setText(rs.getString("cust_name"));
                    txtCusPho.setText(rs.getString("cust_phone"));
                    txtcusfax.setText(rs.getString("cust_fax"));
                    txtcustadd.setText(rs.getString("cust_address"));
                    txtPic.setText(rs.getString("pic_name"));
                    txtPicPho.setText(rs.getString("pic_phone"));
                    txtPicHp.setText(rs.getString("pic_mobile"));
                    txtPicMail.setText(rs.getString("pic_email"));
                    txtPicAdd.setText(rs.getString("pic_address"));
                    txtdetails.setText(rs.getString("details"));
                submit=Integer.parseInt(rs.getString("_submitted"));
                txtsolution.setText(rs.getString("solution"));
                conf=Integer.parseInt(rs.getString("confirmed"));
//            System.out.println("jalan klik 2");
            }
        }catch(Exception e){
            System.out.println(e);

        }
      if(conf==2){
          ckconf.setSelected(true);
      }else{
          ckconf.setSelected(false);
      }

      }
        
        public static void start() {
        cccs_OutBound.startTime = System.currentTimeMillis();
    }


    public static void stop() {
        cccs_OutBound.stopTime = System.currentTimeMillis();
    }


    //elaspsed time in seconds
    public static long duration() {
        if (running) {
            elapsed = ((stopTime - startTime) / 1000);
        }
        else {
            elapsed = ((System.currentTimeMillis() - startTime) / 1000);

        long hours = elapsed / 3600,
                remainder = elapsed % 3600,
                minutes = remainder / 60,
                seconds = remainder % 60;

        String ho=(hours<10 ? "0" : "")+hours,
                menit=(minutes<10 ? "0" : "")+minutes,
                detik=(seconds<10 ? "0" : "")+seconds;
        lbldurasi.setText(ho+":"+menit+":"+detik);
        }

        return elapsed;
    }

    public void dataregis(){
          try{
             int row=0;
              sql="select pabx_host, inbound_ext, outbound_ext from user_account where username='"+CCanj.lbluser.getText()+"'";
              rs=CCanj.jconn.SQLExecuteRS(sql, CCanj.conn);
//              System.out.println(sql);

            while(rs.next()){
                pabx=rs.getString(1);
                in_ext=rs.getString(2);
                out_ext=rs.getString(3);
            }
        }catch(Exception exc){
            System.err.println(exc.getMessage());
        }
    }

    public static Action duration = new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                duration();
            }
       };
       private void usrlvl(){
                try{
                    sql="select _level from user_account where username='"+CCanj.lbluser.getText()+"'";
                    rs=CCanj.jconn.SQLExecuteRS(sql, CCanj.conn);
                    while(rs.next()){
                        usrlvl=rs.getString(1);
                    }
                }catch(Exception e){
                    System.out.print(e);
                }
            }
       private void stt(){
                try{
                    sql="select _status, assign_dept from tickets where ticket_id='"+Tic.id+"' and ticket_no='"+txtnotic.getText()+"'";
                    rs=CCanj.jconn.SQLExecuteRS(sql, CCanj.conn);
                    while(rs.next()){
                        status=Integer.parseInt(rs.getString(1));
                        asdep=Integer.parseInt(rs.getString(2));
                    }
                }catch(Exception e){
                    System.out.print(e);
                }
            }
       private void showCaltype(){
        try{
            cbcaltype.removeAllItems();

            sql="select data from _callertype";
            rs=CCanj.jconn.SQLExecuteRS(sql,CCanj.conn);
            while(rs.next()){
                cbcaltype.addItem(rs.getString(1));
            }
        }catch(Exception e){
            System.out.println(e);

        }
    }
       
       private void showCust(){
        try{
            cbcust.removeAllItems();
            cbcust.addItem("Others");

            sql="select distinct(cust_name) from customer_order order by cust_name";
            rs=CCanj.jconn.SQLExecuteRS(sql,CCanj.conn);
            while(rs.next()){
                cbcust.addItem(rs.getString(1));
            }
            cbcust.setSelectedIndex(-1);
        }catch(Exception e){
            System.out.println(e);

        }
    }
}
